import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IEnterpriseLmsCertification } from "../../../../structures/IEnterpriseLmsCertification";
import { IPageIEnterpriseLmsCertification } from "../../../../structures/IPageIEnterpriseLmsCertification";
export * as certificationExpirations from "./certificationExpirations/index";

/**
 * Create a new certification.
 *
 * This POST operation creates a new certification under the tenant.
 *
 * Only users with organizationAdmin role can create certifications.
 *
 * The request body includes all necessary certification creation data.
 *
 * The response body contains the newly created certification entity.
 *
 * Errors can occur if validation fails or required data is missing.
 *
 * No path parameters are required.
 *
 * This operation ensures tenant data isolation during creation.
 *
 * @param props.connection
 * @param props.body Certification creation data
 * @path /enterpriseLms/organizationAdmin/certifications
 * @accessor api.functional.enterpriseLms.organizationAdmin.certifications.createCertification
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function createCertification(
  connection: IConnection,
  props: createCertification.Props,
): Promise<createCertification.Response> {
  return true === connection.simulate
    ? createCertification.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createCertification.METADATA,
          path: createCertification.path(),
          status: null,
        },
        props.body,
      );
}
export namespace createCertification {
  export type Props = {
    /** Certification creation data */
    body: IEnterpriseLmsCertification.ICreate;
  };
  export type Body = IEnterpriseLmsCertification.ICreate;
  export type Response = IEnterpriseLmsCertification;

  export const METADATA = {
    method: "POST",
    path: "/enterpriseLms/organizationAdmin/certifications",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/enterpriseLms/organizationAdmin/certifications";
  export const random = (): IEnterpriseLmsCertification =>
    typia.random<IEnterpriseLmsCertification>();
  export const simulate = (
    connection: IConnection,
    props: createCertification.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: createCertification.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Search and list paginated tenant certifications.
 *
 * This PATCH operation allows clients to search and retrieve certifications for
 * the tenant with advanced filtering, sorting, and pagination options.
 *
 * It supports querying certifications by code, name, status, and lifecycle
 * state.
 *
 * Only authorized users with roles organizationAdmin or departmentManager can
 * perform this operation.
 *
 * The response includes paginated summary certification information to optimize
 * list rendering.
 *
 * Errors may occur due to invalid search filters or insufficient permissions.
 *
 * This operation requires a request body with search parameters.
 *
 * The response body returns a paginated list of certifications matching the
 * search criteria.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for
 *   certifications
 * @path /enterpriseLms/organizationAdmin/certifications
 * @accessor api.functional.enterpriseLms.organizationAdmin.certifications.searchCertifications
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function searchCertifications(
  connection: IConnection,
  props: searchCertifications.Props,
): Promise<searchCertifications.Response> {
  return true === connection.simulate
    ? searchCertifications.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...searchCertifications.METADATA,
          path: searchCertifications.path(),
          status: null,
        },
        props.body,
      );
}
export namespace searchCertifications {
  export type Props = {
    /** Search criteria and pagination parameters for certifications */
    body: IEnterpriseLmsCertification.IRequest;
  };
  export type Body = IEnterpriseLmsCertification.IRequest;
  export type Response = IPageIEnterpriseLmsCertification.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/enterpriseLms/organizationAdmin/certifications",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/enterpriseLms/organizationAdmin/certifications";
  export const random = (): IPageIEnterpriseLmsCertification.ISummary =>
    typia.random<IPageIEnterpriseLmsCertification.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: searchCertifications.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: searchCertifications.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve certification detail by ID.
 *
 * This GET operation returns detailed information for the certification
 * identified by certificationId.
 *
 * Only users with organizationAdmin or departmentManager roles have access.
 *
 * The response includes all relevant certification data for use in UI or
 * reporting.
 *
 * If the certification is not found, an error response is returned.
 *
 * No request body is required.
 *
 * The response body contains a complete certification entity.
 *
 * @param props.connection
 * @param props.certificationId Unique identifier of the certification
 * @path /enterpriseLms/organizationAdmin/certifications/:certificationId
 * @accessor api.functional.enterpriseLms.organizationAdmin.certifications.atCertification
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function atCertification(
  connection: IConnection,
  props: atCertification.Props,
): Promise<atCertification.Response> {
  return true === connection.simulate
    ? atCertification.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...atCertification.METADATA,
          path: atCertification.path(props),
          status: null,
        },
      );
}
export namespace atCertification {
  export type Props = {
    /** Unique identifier of the certification */
    certificationId: string & tags.Format<"uuid">;
  };
  export type Response = IEnterpriseLmsCertification;

  export const METADATA = {
    method: "GET",
    path: "/enterpriseLms/organizationAdmin/certifications/:certificationId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/enterpriseLms/organizationAdmin/certifications/${encodeURIComponent(props.certificationId ?? "null")}`;
  export const random = (): IEnterpriseLmsCertification =>
    typia.random<IEnterpriseLmsCertification>();
  export const simulate = (
    connection: IConnection,
    props: atCertification.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: atCertification.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("certificationId")(() =>
        typia.assert(props.certificationId),
      );
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update certification details by certification ID.
 *
 * Update an existing certification identified by its unique ID.
 *
 * This API modifies the certification details such as name, description, and
 * status parameters. It ensures that only authorized users with proper roles
 * (e.g., organization administrators) can perform this operation, consistent
 * with multi-tenant data isolation in the Enterprise LMS.
 *
 * The certification entity corresponds to the enterprise_lms_certifications
 * table in the Prisma schema, containing fields like code, name, description,
 * status, and timestamps.
 *
 * Validation of input data will ensure compliance with field constraints.
 *
 * If the certification is soft deleted (deleted_at not null), the update
 * operation will fail or require prior restoration.
 *
 * Importantly, this operation does not alter related expiration policies or
 * certificate issuances; those require separate endpoint management.
 *
 * Errors such as unauthorized access, invalid IDs, or validation failures must
 * be handled with appropriate HTTP response codes and messages.
 *
 * @param props.connection
 * @param props.certificationId Unique identifier of the certification to update
 * @param props.body Updated certification data
 * @path /enterpriseLms/organizationAdmin/certifications/:certificationId
 * @accessor api.functional.enterpriseLms.organizationAdmin.certifications.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /** Unique identifier of the certification to update */
    certificationId: string & tags.Format<"uuid">;

    /** Updated certification data */
    body: IEnterpriseLmsCertification.IUpdate;
  };
  export type Body = IEnterpriseLmsCertification.IUpdate;
  export type Response = IEnterpriseLmsCertification;

  export const METADATA = {
    method: "PUT",
    path: "/enterpriseLms/organizationAdmin/certifications/:certificationId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/enterpriseLms/organizationAdmin/certifications/${encodeURIComponent(props.certificationId ?? "null")}`;
  export const random = (): IEnterpriseLmsCertification =>
    typia.random<IEnterpriseLmsCertification>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("certificationId")(() =>
        typia.assert(props.certificationId),
      );
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Soft delete a certification by ID.
 *
 * Delete (soft delete) a certification by ID.
 *
 * Sets the 'deleted_at' timestamp to mark the certification as deleted without
 * physically removing it from the database.
 *
 * This soft deletion maintains historical data integrity for audit and
 * compliance.
 *
 * Only users with sufficient privileges can perform this operation.
 *
 * Associated expirations and issuances remain unchanged and should be handled
 * separately.
 *
 * The operation returns no content upon success.
 *
 * Errors include access denial, non-existent certification, or conflicts if
 * deletion violates constraints.
 *
 * @param props.connection
 * @param props.certificationId Unique identifier of the certification to delete
 * @path /enterpriseLms/organizationAdmin/certifications/:certificationId
 * @accessor api.functional.enterpriseLms.organizationAdmin.certifications.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique identifier of the certification to delete */
    certificationId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/enterpriseLms/organizationAdmin/certifications/:certificationId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/enterpriseLms/organizationAdmin/certifications/${encodeURIComponent(props.certificationId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("certificationId")(() =>
        typia.assert(props.certificationId),
      );
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
