import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IJobPerformanceEvalJobGroups } from "../../../../structures/IJobPerformanceEvalJobGroups";
import { IPageIJobPerformanceEvalJobGroups } from "../../../../structures/IPageIJobPerformanceEvalJobGroups";
import { IJobPerformanceEvalJobGroup } from "../../../../structures/IJobPerformanceEvalJobGroup";
export * as jobSeries from "./jobSeries/index";

/**
 * Search and retrieve paginated list of job groups.
 *
 * Retrieve filtered and paginated list of job groups in the job performance
 * evaluation system. The operation supports criteria such as code, name, and
 * creation range filtering.
 *
 * Job groups represent the highest level category of job hierarchy managed
 * within the system.
 *
 * This API endpoint provides pagination and sorting features for efficient data
 * handling.
 *
 * Only authorized users with employee or manager permissions can access this
 * resource.
 *
 * The response provides summarized data of job groups suitable for listings.
 *
 * @param props.connection
 * @param props.body Job group search and pagination parameters
 * @path /jobPerformanceEval/employee/jobGroups
 * @accessor api.functional.jobPerformanceEval.employee.jobGroups.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Job group search and pagination parameters */
    body: IJobPerformanceEvalJobGroups.IRequest;
  };
  export type Body = IJobPerformanceEvalJobGroups.IRequest;
  export type Response = IPageIJobPerformanceEvalJobGroups.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/jobPerformanceEval/employee/jobGroups",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/jobPerformanceEval/employee/jobGroups";
  export const random = (): IPageIJobPerformanceEvalJobGroups.ISummary =>
    typia.random<IPageIJobPerformanceEvalJobGroups.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a job group by its ID from the job_performance_eval_job_groups
 * table.
 *
 * Retrieve detailed information of a specific job group identified by its
 * unique ID.
 *
 * This API retrieves data from the job_performance_eval_job_groups table,
 * including the unique code, name, and optional description of the job group.
 * It is intended for authenticated users who need to view job group details for
 * management or reporting purposes.
 *
 * Security considerations include requiring authenticated access to prevent
 * unauthorized data exposure. The system validates the UUID format of the job
 * group ID.
 *
 * Related operations include creating, updating, and deleting job groups which
 * manage the lifecycle of job group records.
 *
 * This operation returns the full job group data including timestamps for
 * creation and last update.
 *
 * Errors such as not found or invalid ID format will result in appropriate HTTP
 * error responses.
 *
 * @param props.connection
 * @param props.id Unique identifier of the job group (UUID)
 * @path /jobPerformanceEval/employee/jobGroups/:id
 * @accessor api.functional.jobPerformanceEval.employee.jobGroups.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the job group (UUID) */
    id: string & tags.Format<"uuid">;
  };
  export type Response = IJobPerformanceEvalJobGroup;

  export const METADATA = {
    method: "GET",
    path: "/jobPerformanceEval/employee/jobGroups/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/jobPerformanceEval/employee/jobGroups/${encodeURIComponent(props.id ?? "null")}`;
  export const random = (): IJobPerformanceEvalJobGroup =>
    typia.random<IJobPerformanceEvalJobGroup>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("id")(() => typia.assert(props.id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
