import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ISubscriptionRenewalGuardianSubscription } from "../../../../structures/ISubscriptionRenewalGuardianSubscription";
import { ISubscriptionRenewalGuardianSubscriptions } from "../../../../structures/ISubscriptionRenewalGuardianSubscriptions";
import { IPageISubscriptionRenewalGuardianSubscriptions } from "../../../../structures/IPageISubscriptionRenewalGuardianSubscriptions";
export * as reminderSettings from "./reminderSettings/index";
export * as upcomingRenewals from "./upcomingRenewals/index";

/**
 * Create a new subscription for the authenticated user.
 *
 * This operation accepts subscription creation data, validates it against
 * business rules, and stores the new subscription in the database. It
 * calculates the next_renewal_at field automatically from started_at and
 * billing_cycle according to the business logic.
 *
 * Uniqueness constraints on (user_id, vendor_id, plan_name) are enforced.
 *
 * Only authenticated users with user role can create subscriptions.
 *
 * No soft delete mechanisms apply; this is a hard create operation.
 *
 * Request Body:
 *
 * - Subscription creation data as
 *   ISubscriptionRenewalGuardianSubscription.ICreate.
 *
 * Response Body:
 *
 * - Newly created subscription including calculated fields.
 *
 * Path Parameters:
 *
 * - None.
 *
 * Security:
 *
 * - Authentication and ownership verified by JWT.
 *
 * This operation is core to user subscription lifecycle management.
 *
 * @param props.connection
 * @param props.body Subscription creation data
 * @path /subscriptionRenewalGuardian/user/subscriptions
 * @accessor api.functional.subscriptionRenewalGuardian.user.subscriptions.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /** Subscription creation data */
    body: ISubscriptionRenewalGuardianSubscription.ICreate;
  };
  export type Body = ISubscriptionRenewalGuardianSubscription.ICreate;
  export type Response = ISubscriptionRenewalGuardianSubscription;

  export const METADATA = {
    method: "POST",
    path: "/subscriptionRenewalGuardian/user/subscriptions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/subscriptionRenewalGuardian/user/subscriptions";
  export const random = (): ISubscriptionRenewalGuardianSubscription =>
    typia.random<ISubscriptionRenewalGuardianSubscription>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Search and retrieve paginated list of subscriptions.
 *
 * This operation allows users to retrieve a filtered and paginated list of
 * their subscriptions from the subscription_renewal_guardian_subscriptions
 * table.
 *
 * Users may specify search criteria in the request body such as filtering by
 * status (ACTIVE, PAUSED, CANCELED), vendor, plan name, or date ranges for
 * next_renewal_at. Pagination is supported via standard limit and offset
 * parameters.
 *
 * Security considerations ensure only the authenticated user's subscriptions
 * are returned unless the requester has admin role with read-only access to all
 * users' subscriptions.
 *
 * The response returns a paginated list of subscription summaries with
 * essential properties for display in UI lists.
 *
 * This operation is critical for enabling users to manage and monitor their
 * subscriptions efficiently.
 *
 * Parameters:
 *
 * - No path parameters.
 *
 * Request Body:
 *
 * - ISubscriptionRenewalGuardianSubscriptions.IRequest: search, filter,
 *   pagination parameters.
 *
 * Response Body:
 *
 * - IPageISubscriptionRenewalGuardianSubscriptions.ISummary: paginated
 *   subscription summaries.
 *
 * Authorization:
 *
 * - Roles: user, admin (both can access but with data filtering logic).
 *
 * Expected errors:
 *
 * - 401 Unauthorized if unauthenticated.
 * - 400 Bad Request for invalid filters.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for subscriptions
 * @path /subscriptionRenewalGuardian/user/subscriptions
 * @accessor api.functional.subscriptionRenewalGuardian.user.subscriptions.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Search criteria and pagination parameters for subscriptions */
    body: ISubscriptionRenewalGuardianSubscriptions.IRequest;
  };
  export type Body = ISubscriptionRenewalGuardianSubscriptions.IRequest;
  export type Response =
    IPageISubscriptionRenewalGuardianSubscriptions.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/subscriptionRenewalGuardian/user/subscriptions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/subscriptionRenewalGuardian/user/subscriptions";
  export const random =
    (): IPageISubscriptionRenewalGuardianSubscriptions.ISummary =>
      typia.random<IPageISubscriptionRenewalGuardianSubscriptions.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed subscription information by ID.
 *
 * Retrieve detailed information of a subscription by its ID.
 *
 * This operation fetches the subscription identified by subscriptionId from the
 * subscription_renewal_guardian_subscriptions table. It includes comprehensive
 * details such as plan name, status, billing cycle, renewal dates, amount,
 * currency, notes, and related vendor and reminder settings.
 *
 * Security ensures that only the owner user or an admin can access the
 * subscription details.
 *
 * Path Parameters:
 *
 * - SubscriptionId: UUID of the subscription to retrieve.
 *
 * This operation is essential for viewing full subscription details in a
 * dedicated UI screen.
 *
 * @param props.connection
 * @param props.subscriptionId Unique identifier of the subscription to retrieve
 * @path /subscriptionRenewalGuardian/user/subscriptions/:subscriptionId
 * @accessor api.functional.subscriptionRenewalGuardian.user.subscriptions.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the subscription to retrieve */
    subscriptionId: string & tags.Format<"uuid">;
  };
  export type Response = ISubscriptionRenewalGuardianSubscription;

  export const METADATA = {
    method: "GET",
    path: "/subscriptionRenewalGuardian/user/subscriptions/:subscriptionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/subscriptionRenewalGuardian/user/subscriptions/${encodeURIComponent(props.subscriptionId ?? "null")}`;
  export const random = (): ISubscriptionRenewalGuardianSubscription =>
    typia.random<ISubscriptionRenewalGuardianSubscription>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("subscriptionId")(() => typia.assert(props.subscriptionId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update subscription by ID.
 *
 * Update an existing subscription identified by subscriptionId.
 *
 * Allows modification of subscription fields except primary key and immutable
 * fields. Validates input and business rules, recalculates next_renewal_at if
 * necessary.
 *
 * Updates are forbidden on CANCELED subscriptions to enforce terminal state.
 *
 * Path Parameters:
 *
 * - SubscriptionId: UUID of the subscription to update.
 *
 * Request Body:
 *
 * - ISubscriptionRenewalGuardianSubscription.IUpdate containing fields to update.
 *
 * Response Body:
 *
 * - Updated subscription details.
 *
 * Authorization ensures only the owner user can update their subscription.
 *
 * This enables users to maintain their subscription information accurately
 * throughout its lifecycle.
 *
 * @param props.connection
 * @param props.subscriptionId Unique identifier of the subscription to update
 * @param props.body Subscription update data
 * @path /subscriptionRenewalGuardian/user/subscriptions/:subscriptionId
 * @accessor api.functional.subscriptionRenewalGuardian.user.subscriptions.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /** Unique identifier of the subscription to update */
    subscriptionId: string & tags.Format<"uuid">;

    /** Subscription update data */
    body: ISubscriptionRenewalGuardianSubscription.IUpdate;
  };
  export type Body = ISubscriptionRenewalGuardianSubscription.IUpdate;
  export type Response = ISubscriptionRenewalGuardianSubscription;

  export const METADATA = {
    method: "PUT",
    path: "/subscriptionRenewalGuardian/user/subscriptions/:subscriptionId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/subscriptionRenewalGuardian/user/subscriptions/${encodeURIComponent(props.subscriptionId ?? "null")}`;
  export const random = (): ISubscriptionRenewalGuardianSubscription =>
    typia.random<ISubscriptionRenewalGuardianSubscription>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("subscriptionId")(() => typia.assert(props.subscriptionId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Delete a subscription by ID.
 *
 * Delete a subscription identified by subscriptionId. Only authorized users
 * with role 'user' can perform this operation. The subscription identified by
 * UUID subscriptionId is removed permanently from the system.
 *
 * This operation requires no request body and produces no response body.
 *
 * HTTP 404 returned if subscription not found or user unauthorized. HTTP 401
 * returned if user not authenticated.
 *
 * @param props.connection
 * @param props.subscriptionId UUID of the subscription to delete
 * @path /subscriptionRenewalGuardian/user/subscriptions/:subscriptionId
 * @accessor api.functional.subscriptionRenewalGuardian.user.subscriptions.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** UUID of the subscription to delete */
    subscriptionId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/subscriptionRenewalGuardian/user/subscriptions/:subscriptionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/subscriptionRenewalGuardian/user/subscriptions/${encodeURIComponent(props.subscriptionId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("subscriptionId")(() => typia.assert(props.subscriptionId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
