import { Module } from "@nestjs/common";

import { AuthSystemadminController } from "./controllers/auth/systemAdmin/AuthSystemadminController";
import { AuthOrganizationadminController } from "./controllers/auth/organizationAdmin/AuthOrganizationadminController";
import { AuthDepartmentheadController } from "./controllers/auth/departmentHead/AuthDepartmentheadController";
import { AuthMedicaldoctorController } from "./controllers/auth/medicalDoctor/AuthMedicaldoctorController";
import { AuthNurseController } from "./controllers/auth/nurse/AuthNurseController";
import { AuthTechnicianController } from "./controllers/auth/technician/AuthTechnicianController";
import { AuthReceptionistController } from "./controllers/auth/receptionist/AuthReceptionistController";
import { AuthPatientController } from "./controllers/auth/patient/AuthPatientController";
import { HealthcareplatformSystemadminOrganizationsController } from "./controllers/healthcarePlatform/systemAdmin/organizations/HealthcareplatformSystemadminOrganizationsController";
import { HealthcareplatformOrganizationadminOrganizationsDepartmentsController } from "./controllers/healthcarePlatform/organizationAdmin/organizations/departments/HealthcareplatformOrganizationadminOrganizationsDepartmentsController";
import { HealthcareplatformDepartmentheadOrganizationsDepartmentsController } from "./controllers/healthcarePlatform/departmentHead/organizations/departments/HealthcareplatformDepartmentheadOrganizationsDepartmentsController";
import { HealthcareplatformSystemadminRolesController } from "./controllers/healthcarePlatform/systemAdmin/roles/HealthcareplatformSystemadminRolesController";
import { HealthcareplatformOrganizationadminRolesController } from "./controllers/healthcarePlatform/organizationAdmin/roles/HealthcareplatformOrganizationadminRolesController";
import { HealthcareplatformSystemadminPermissionsController } from "./controllers/healthcarePlatform/systemAdmin/permissions/HealthcareplatformSystemadminPermissionsController";
import { HealthcareplatformSystemadminOrgdepartmentassignmentsController } from "./controllers/healthcarePlatform/systemAdmin/orgDepartmentAssignments/HealthcareplatformSystemadminOrgdepartmentassignmentsController";
import { HealthcareplatformOrganizationadminOrgdepartmentassignmentsController } from "./controllers/healthcarePlatform/organizationAdmin/orgDepartmentAssignments/HealthcareplatformOrganizationadminOrgdepartmentassignmentsController";
import { HealthcareplatformSystemadminUserorgassignmentsController } from "./controllers/healthcarePlatform/systemAdmin/userOrgAssignments/HealthcareplatformSystemadminUserorgassignmentsController";
import { HealthcareplatformOrganizationadminUserorgassignmentsController } from "./controllers/healthcarePlatform/organizationAdmin/userOrgAssignments/HealthcareplatformOrganizationadminUserorgassignmentsController";
import { HealthcareplatformSystemadminConfigurationController } from "./controllers/healthcarePlatform/systemAdmin/configuration/HealthcareplatformSystemadminConfigurationController";
import { HealthcareplatformOrganizationadminConfigurationController } from "./controllers/healthcarePlatform/organizationAdmin/configuration/HealthcareplatformOrganizationadminConfigurationController";
import { HealthcareplatformSystemadminLocalesettingsController } from "./controllers/healthcarePlatform/systemAdmin/localeSettings/HealthcareplatformSystemadminLocalesettingsController";
import { HealthcareplatformOrganizationadminLocalesettingsController } from "./controllers/healthcarePlatform/organizationAdmin/localeSettings/HealthcareplatformOrganizationadminLocalesettingsController";
import { HealthcareplatformSystemadminSystemadminsController } from "./controllers/healthcarePlatform/systemAdmin/systemadmins/HealthcareplatformSystemadminSystemadminsController";
import { HealthcareplatformSystemadminOrganizationadminsController } from "./controllers/healthcarePlatform/systemAdmin/organizationadmins/HealthcareplatformSystemadminOrganizationadminsController";
import { HealthcareplatformOrganizationadminOrganizationadminsController } from "./controllers/healthcarePlatform/organizationAdmin/organizationadmins/HealthcareplatformOrganizationadminOrganizationadminsController";
import { HealthcareplatformSystemadminDepartmentheadsController } from "./controllers/healthcarePlatform/systemAdmin/departmentheads/HealthcareplatformSystemadminDepartmentheadsController";
import { HealthcareplatformOrganizationadminDepartmentheadsController } from "./controllers/healthcarePlatform/organizationAdmin/departmentheads/HealthcareplatformOrganizationadminDepartmentheadsController";
import { HealthcareplatformOrganizationadminMedicaldoctorsController } from "./controllers/healthcarePlatform/organizationAdmin/medicaldoctors/HealthcareplatformOrganizationadminMedicaldoctorsController";
import { HealthcareplatformSystemadminMedicaldoctorsController } from "./controllers/healthcarePlatform/systemAdmin/medicaldoctors/HealthcareplatformSystemadminMedicaldoctorsController";
import { HealthcareplatformOrganizationadminNursesController } from "./controllers/healthcarePlatform/organizationAdmin/nurses/HealthcareplatformOrganizationadminNursesController";
import { HealthcareplatformDepartmentheadNursesController } from "./controllers/healthcarePlatform/departmentHead/nurses/HealthcareplatformDepartmentheadNursesController";
import { HealthcareplatformSystemadminNursesController } from "./controllers/healthcarePlatform/systemAdmin/nurses/HealthcareplatformSystemadminNursesController";
import { HealthcareplatformSystemadminTechniciansController } from "./controllers/healthcarePlatform/systemAdmin/technicians/HealthcareplatformSystemadminTechniciansController";
import { HealthcareplatformOrganizationadminTechniciansController } from "./controllers/healthcarePlatform/organizationAdmin/technicians/HealthcareplatformOrganizationadminTechniciansController";
import { HealthcareplatformSystemadminReceptionistsController } from "./controllers/healthcarePlatform/systemAdmin/receptionists/HealthcareplatformSystemadminReceptionistsController";
import { HealthcareplatformOrganizationadminReceptionistsController } from "./controllers/healthcarePlatform/organizationAdmin/receptionists/HealthcareplatformOrganizationadminReceptionistsController";
import { HealthcareplatformOrganizationadminPatientsController } from "./controllers/healthcarePlatform/organizationAdmin/patients/HealthcareplatformOrganizationadminPatientsController";
import { HealthcareplatformMedicaldoctorPatientsController } from "./controllers/healthcarePlatform/medicalDoctor/patients/HealthcareplatformMedicaldoctorPatientsController";
import { HealthcareplatformNursePatientsController } from "./controllers/healthcarePlatform/nurse/patients/HealthcareplatformNursePatientsController";
import { HealthcareplatformReceptionistPatientsController } from "./controllers/healthcarePlatform/receptionist/patients/HealthcareplatformReceptionistPatientsController";
import { HealthcareplatformPatientPatientsController } from "./controllers/healthcarePlatform/patient/patients/HealthcareplatformPatientPatientsController";
import { HealthcareplatformSystemadminUserauthenticationsController } from "./controllers/healthcarePlatform/systemAdmin/userAuthentications/HealthcareplatformSystemadminUserauthenticationsController";
import { HealthcareplatformOrganizationadminUserauthenticationsController } from "./controllers/healthcarePlatform/organizationAdmin/userAuthentications/HealthcareplatformOrganizationadminUserauthenticationsController";
import { HealthcareplatformSystemadminAuthsessionsController } from "./controllers/healthcarePlatform/systemAdmin/authSessions/HealthcareplatformSystemadminAuthsessionsController";
import { HealthcareplatformSystemadminUsermfafactorsController } from "./controllers/healthcarePlatform/systemAdmin/userMfaFactors/HealthcareplatformSystemadminUsermfafactorsController";
import { HealthcareplatformOrganizationadminUsermfafactorsController } from "./controllers/healthcarePlatform/organizationAdmin/userMfaFactors/HealthcareplatformOrganizationadminUsermfafactorsController";
import { HealthcareplatformSystemadminUsercredentialsController } from "./controllers/healthcarePlatform/systemAdmin/userCredentials/HealthcareplatformSystemadminUsercredentialsController";
import { HealthcareplatformOrganizationadminUsercredentialsController } from "./controllers/healthcarePlatform/organizationAdmin/userCredentials/HealthcareplatformOrganizationadminUsercredentialsController";
import { HealthcareplatformSystemadminUserlicenseverificationsController } from "./controllers/healthcarePlatform/systemAdmin/userLicenseVerifications/HealthcareplatformSystemadminUserlicenseverificationsController";
import { HealthcareplatformOrganizationadminUserlicenseverificationsController } from "./controllers/healthcarePlatform/organizationAdmin/userLicenseVerifications/HealthcareplatformOrganizationadminUserlicenseverificationsController";
import { HealthcareplatformOrganizationadminPatientrecordsController } from "./controllers/healthcarePlatform/organizationAdmin/patientRecords/HealthcareplatformOrganizationadminPatientrecordsController";
import { HealthcareplatformMedicaldoctorPatientrecordsController } from "./controllers/healthcarePlatform/medicalDoctor/patientRecords/HealthcareplatformMedicaldoctorPatientrecordsController";
import { HealthcareplatformNursePatientrecordsController } from "./controllers/healthcarePlatform/nurse/patientRecords/HealthcareplatformNursePatientrecordsController";
import { HealthcareplatformDepartmentheadPatientrecordsController } from "./controllers/healthcarePlatform/departmentHead/patientRecords/HealthcareplatformDepartmentheadPatientrecordsController";
import { HealthcareplatformSystemadminPatientrecordsController } from "./controllers/healthcarePlatform/systemAdmin/patientRecords/HealthcareplatformSystemadminPatientrecordsController";
import { HealthcareplatformReceptionistPatientrecordsController } from "./controllers/healthcarePlatform/receptionist/patientRecords/HealthcareplatformReceptionistPatientrecordsController";
import { HealthcareplatformMedicaldoctorPatientrecordsEncountersController } from "./controllers/healthcarePlatform/medicalDoctor/patientRecords/encounters/HealthcareplatformMedicaldoctorPatientrecordsEncountersController";
import { HealthcareplatformNursePatientrecordsEncountersController } from "./controllers/healthcarePlatform/nurse/patientRecords/encounters/HealthcareplatformNursePatientrecordsEncountersController";
import { HealthcareplatformOrganizationadminPatientrecordsEncountersController } from "./controllers/healthcarePlatform/organizationAdmin/patientRecords/encounters/HealthcareplatformOrganizationadminPatientrecordsEncountersController";
import { HealthcareplatformDepartmentheadPatientrecordsEncountersController } from "./controllers/healthcarePlatform/departmentHead/patientRecords/encounters/HealthcareplatformDepartmentheadPatientrecordsEncountersController";
import { HealthcareplatformSystemadminPatientrecordsEncountersEhrversionsController } from "./controllers/healthcarePlatform/systemAdmin/patientRecords/encounters/ehrVersions/HealthcareplatformSystemadminPatientrecordsEncountersEhrversionsController";
import { HealthcareplatformMedicaldoctorPatientrecordsEncountersEhrversionsController } from "./controllers/healthcarePlatform/medicalDoctor/patientRecords/encounters/ehrVersions/HealthcareplatformMedicaldoctorPatientrecordsEncountersEhrversionsController";
import { HealthcareplatformNursePatientrecordsEncountersEhrversionsController } from "./controllers/healthcarePlatform/nurse/patientRecords/encounters/ehrVersions/HealthcareplatformNursePatientrecordsEncountersEhrversionsController";
import { HealthcareplatformDepartmentheadPatientrecordsEncountersEhrversionsController } from "./controllers/healthcarePlatform/departmentHead/patientRecords/encounters/ehrVersions/HealthcareplatformDepartmentheadPatientrecordsEncountersEhrversionsController";
import { HealthcareplatformDepartmentheadPatientrecordsRecordamendmentsController } from "./controllers/healthcarePlatform/departmentHead/patientRecords/recordAmendments/HealthcareplatformDepartmentheadPatientrecordsRecordamendmentsController";
import { HealthcareplatformMedicaldoctorPatientrecordsRecordamendmentsController } from "./controllers/healthcarePlatform/medicalDoctor/patientRecords/recordAmendments/HealthcareplatformMedicaldoctorPatientrecordsRecordamendmentsController";
import { HealthcareplatformNursePatientrecordsRecordamendmentsController } from "./controllers/healthcarePlatform/nurse/patientRecords/recordAmendments/HealthcareplatformNursePatientrecordsRecordamendmentsController";
import { HealthcareplatformOrganizationadminPatientrecordsRecordamendmentsController } from "./controllers/healthcarePlatform/organizationAdmin/patientRecords/recordAmendments/HealthcareplatformOrganizationadminPatientrecordsRecordamendmentsController";
import { HealthcareplatformSystemadminPatientrecordsRecordamendmentsController } from "./controllers/healthcarePlatform/systemAdmin/patientRecords/recordAmendments/HealthcareplatformSystemadminPatientrecordsRecordamendmentsController";
import { HealthcareplatformSystemadminPatientrecordsRecordaudittrailsController } from "./controllers/healthcarePlatform/systemAdmin/patientRecords/recordAuditTrails/HealthcareplatformSystemadminPatientrecordsRecordaudittrailsController";
import { HealthcareplatformSystemadminPatientrecordsMedicalimagesController } from "./controllers/healthcarePlatform/systemAdmin/patientRecords/medicalImages/HealthcareplatformSystemadminPatientrecordsMedicalimagesController";
import { HealthcareplatformMedicaldoctorPatientrecordsMedicalimagesController } from "./controllers/healthcarePlatform/medicalDoctor/patientRecords/medicalImages/HealthcareplatformMedicaldoctorPatientrecordsMedicalimagesController";
import { HealthcareplatformNursePatientrecordsMedicalimagesController } from "./controllers/healthcarePlatform/nurse/patientRecords/medicalImages/HealthcareplatformNursePatientrecordsMedicalimagesController";
import { HealthcareplatformTechnicianPatientrecordsMedicalimagesController } from "./controllers/healthcarePlatform/technician/patientRecords/medicalImages/HealthcareplatformTechnicianPatientrecordsMedicalimagesController";
import { HealthcareplatformPatientPatientrecordsMedicalimagesController } from "./controllers/healthcarePlatform/patient/patientRecords/medicalImages/HealthcareplatformPatientPatientrecordsMedicalimagesController";
import { HealthcareplatformMedicaldoctorPatientrecordsEncountersLabresultsController } from "./controllers/healthcarePlatform/medicalDoctor/patientRecords/encounters/labResults/HealthcareplatformMedicaldoctorPatientrecordsEncountersLabresultsController";
import { HealthcareplatformNursePatientrecordsEncountersLabresultsController } from "./controllers/healthcarePlatform/nurse/patientRecords/encounters/labResults/HealthcareplatformNursePatientrecordsEncountersLabresultsController";
import { HealthcareplatformTechnicianPatientrecordsEncountersLabresultsController } from "./controllers/healthcarePlatform/technician/patientRecords/encounters/labResults/HealthcareplatformTechnicianPatientrecordsEncountersLabresultsController";
import { HealthcareplatformDepartmentheadPatientrecordsEncountersLabresultsController } from "./controllers/healthcarePlatform/departmentHead/patientRecords/encounters/labResults/HealthcareplatformDepartmentheadPatientrecordsEncountersLabresultsController";
import { HealthcareplatformOrganizationadminPatientrecordsEncountersLabresultsController } from "./controllers/healthcarePlatform/organizationAdmin/patientRecords/encounters/labResults/HealthcareplatformOrganizationadminPatientrecordsEncountersLabresultsController";
import { HealthcareplatformMedicaldoctorPatientrecordsEncountersVitalsController } from "./controllers/healthcarePlatform/medicalDoctor/patientRecords/encounters/vitals/HealthcareplatformMedicaldoctorPatientrecordsEncountersVitalsController";
import { HealthcareplatformNursePatientrecordsEncountersVitalsController } from "./controllers/healthcarePlatform/nurse/patientRecords/encounters/vitals/HealthcareplatformNursePatientrecordsEncountersVitalsController";
import { HealthcareplatformDepartmentheadPatientrecordsEncountersVitalsController } from "./controllers/healthcarePlatform/departmentHead/patientRecords/encounters/vitals/HealthcareplatformDepartmentheadPatientrecordsEncountersVitalsController";
import { HealthcareplatformSystemadminAppointmentsController } from "./controllers/healthcarePlatform/systemAdmin/appointments/HealthcareplatformSystemadminAppointmentsController";
import { HealthcareplatformOrganizationadminAppointmentsController } from "./controllers/healthcarePlatform/organizationAdmin/appointments/HealthcareplatformOrganizationadminAppointmentsController";
import { HealthcareplatformDepartmentheadAppointmentsController } from "./controllers/healthcarePlatform/departmentHead/appointments/HealthcareplatformDepartmentheadAppointmentsController";
import { HealthcareplatformMedicaldoctorAppointmentsController } from "./controllers/healthcarePlatform/medicalDoctor/appointments/HealthcareplatformMedicaldoctorAppointmentsController";
import { HealthcareplatformNurseAppointmentsController } from "./controllers/healthcarePlatform/nurse/appointments/HealthcareplatformNurseAppointmentsController";
import { HealthcareplatformTechnicianAppointmentsController } from "./controllers/healthcarePlatform/technician/appointments/HealthcareplatformTechnicianAppointmentsController";
import { HealthcareplatformReceptionistAppointmentsController } from "./controllers/healthcarePlatform/receptionist/appointments/HealthcareplatformReceptionistAppointmentsController";
import { HealthcareplatformPatientAppointmentsController } from "./controllers/healthcarePlatform/patient/appointments/HealthcareplatformPatientAppointmentsController";
import { HealthcareplatformReceptionistAppointmentsRemindersController } from "./controllers/healthcarePlatform/receptionist/appointments/reminders/HealthcareplatformReceptionistAppointmentsRemindersController";
import { HealthcareplatformOrganizationadminAppointmentsRemindersController } from "./controllers/healthcarePlatform/organizationAdmin/appointments/reminders/HealthcareplatformOrganizationadminAppointmentsRemindersController";
import { HealthcareplatformDepartmentheadAppointmentsRemindersController } from "./controllers/healthcarePlatform/departmentHead/appointments/reminders/HealthcareplatformDepartmentheadAppointmentsRemindersController";
import { HealthcareplatformMedicaldoctorAppointmentsRemindersController } from "./controllers/healthcarePlatform/medicalDoctor/appointments/reminders/HealthcareplatformMedicaldoctorAppointmentsRemindersController";
import { HealthcareplatformSystemadminAppointmentsRemindersController } from "./controllers/healthcarePlatform/systemAdmin/appointments/reminders/HealthcareplatformSystemadminAppointmentsRemindersController";
import { HealthcareplatformNurseAppointmentsRemindersController } from "./controllers/healthcarePlatform/nurse/appointments/reminders/HealthcareplatformNurseAppointmentsRemindersController";
import { HealthcareplatformTechnicianAppointmentsRemindersController } from "./controllers/healthcarePlatform/technician/appointments/reminders/HealthcareplatformTechnicianAppointmentsRemindersController";
import { HealthcareplatformPatientAppointmentsRemindersController } from "./controllers/healthcarePlatform/patient/appointments/reminders/HealthcareplatformPatientAppointmentsRemindersController";
import { HealthcareplatformSystemadminAppointmentsWaitlistsController } from "./controllers/healthcarePlatform/systemAdmin/appointments/waitlists/HealthcareplatformSystemadminAppointmentsWaitlistsController";
import { HealthcareplatformOrganizationadminAppointmentsWaitlistsController } from "./controllers/healthcarePlatform/organizationAdmin/appointments/waitlists/HealthcareplatformOrganizationadminAppointmentsWaitlistsController";
import { HealthcareplatformDepartmentheadAppointmentsWaitlistsController } from "./controllers/healthcarePlatform/departmentHead/appointments/waitlists/HealthcareplatformDepartmentheadAppointmentsWaitlistsController";
import { HealthcareplatformMedicaldoctorAppointmentsWaitlistsController } from "./controllers/healthcarePlatform/medicalDoctor/appointments/waitlists/HealthcareplatformMedicaldoctorAppointmentsWaitlistsController";
import { HealthcareplatformNurseAppointmentsWaitlistsController } from "./controllers/healthcarePlatform/nurse/appointments/waitlists/HealthcareplatformNurseAppointmentsWaitlistsController";
import { HealthcareplatformTechnicianAppointmentsWaitlistsController } from "./controllers/healthcarePlatform/technician/appointments/waitlists/HealthcareplatformTechnicianAppointmentsWaitlistsController";
import { HealthcareplatformReceptionistAppointmentsWaitlistsController } from "./controllers/healthcarePlatform/receptionist/appointments/waitlists/HealthcareplatformReceptionistAppointmentsWaitlistsController";
import { HealthcareplatformPatientAppointmentsWaitlistsController } from "./controllers/healthcarePlatform/patient/appointments/waitlists/HealthcareplatformPatientAppointmentsWaitlistsController";
import { HealthcareplatformReceptionistAppointmentstatusesController } from "./controllers/healthcarePlatform/receptionist/appointmentStatuses/HealthcareplatformReceptionistAppointmentstatusesController";
import { HealthcareplatformOrganizationadminAppointmentstatusesController } from "./controllers/healthcarePlatform/organizationAdmin/appointmentStatuses/HealthcareplatformOrganizationadminAppointmentstatusesController";
import { HealthcareplatformSystemadminAppointmentstatusesController } from "./controllers/healthcarePlatform/systemAdmin/appointmentStatuses/HealthcareplatformSystemadminAppointmentstatusesController";
import { HealthcareplatformSystemadminResourceschedulesController } from "./controllers/healthcarePlatform/systemAdmin/resourceSchedules/HealthcareplatformSystemadminResourceschedulesController";
import { HealthcareplatformOrganizationadminResourceschedulesController } from "./controllers/healthcarePlatform/organizationAdmin/resourceSchedules/HealthcareplatformOrganizationadminResourceschedulesController";
import { HealthcareplatformOrganizationadminRoomreservationsController } from "./controllers/healthcarePlatform/organizationAdmin/roomReservations/HealthcareplatformOrganizationadminRoomreservationsController";
import { HealthcareplatformDepartmentheadRoomreservationsController } from "./controllers/healthcarePlatform/departmentHead/roomReservations/HealthcareplatformDepartmentheadRoomreservationsController";
import { HealthcareplatformReceptionistRoomreservationsController } from "./controllers/healthcarePlatform/receptionist/roomReservations/HealthcareplatformReceptionistRoomreservationsController";
import { HealthcareplatformSystemadminRoomreservationsController } from "./controllers/healthcarePlatform/systemAdmin/roomReservations/HealthcareplatformSystemadminRoomreservationsController";
import { HealthcareplatformSystemadminEquipmentreservationsController } from "./controllers/healthcarePlatform/systemAdmin/equipmentReservations/HealthcareplatformSystemadminEquipmentreservationsController";
import { HealthcareplatformOrganizationadminEquipmentreservationsController } from "./controllers/healthcarePlatform/organizationAdmin/equipmentReservations/HealthcareplatformOrganizationadminEquipmentreservationsController";
import { HealthcareplatformDepartmentheadEquipmentreservationsController } from "./controllers/healthcarePlatform/departmentHead/equipmentReservations/HealthcareplatformDepartmentheadEquipmentreservationsController";
import { HealthcareplatformOrganizationadminCalendarsettingsController } from "./controllers/healthcarePlatform/organizationAdmin/calendarSettings/HealthcareplatformOrganizationadminCalendarsettingsController";
import { HealthcareplatformOrganizationadminTelemedicinesessionsController } from "./controllers/healthcarePlatform/organizationAdmin/telemedicineSessions/HealthcareplatformOrganizationadminTelemedicinesessionsController";
import { HealthcareplatformMedicaldoctorTelemedicinesessionsController } from "./controllers/healthcarePlatform/medicalDoctor/telemedicineSessions/HealthcareplatformMedicaldoctorTelemedicinesessionsController";
import { HealthcareplatformSystemadminTelemedicinesessionsController } from "./controllers/healthcarePlatform/systemAdmin/telemedicineSessions/HealthcareplatformSystemadminTelemedicinesessionsController";
import { HealthcareplatformSystemadminBillinginvoicesController } from "./controllers/healthcarePlatform/systemAdmin/billingInvoices/HealthcareplatformSystemadminBillinginvoicesController";
import { HealthcareplatformOrganizationadminBillinginvoicesController } from "./controllers/healthcarePlatform/organizationAdmin/billingInvoices/HealthcareplatformOrganizationadminBillinginvoicesController";
import { HealthcareplatformDepartmentheadBillinginvoicesController } from "./controllers/healthcarePlatform/departmentHead/billingInvoices/HealthcareplatformDepartmentheadBillinginvoicesController";
import { HealthcareplatformPatientBillinginvoicesController } from "./controllers/healthcarePlatform/patient/billingInvoices/HealthcareplatformPatientBillinginvoicesController";
import { HealthcareplatformOrganizationadminBillinginvoicesBillingitemsController } from "./controllers/healthcarePlatform/organizationAdmin/billingInvoices/billingItems/HealthcareplatformOrganizationadminBillinginvoicesBillingitemsController";
import { HealthcareplatformDepartmentheadBillinginvoicesBillingitemsController } from "./controllers/healthcarePlatform/departmentHead/billingInvoices/billingItems/HealthcareplatformDepartmentheadBillinginvoicesBillingitemsController";
import { HealthcareplatformOrganizationadminBillingcodesController } from "./controllers/healthcarePlatform/organizationAdmin/billingCodes/HealthcareplatformOrganizationadminBillingcodesController";
import { HealthcareplatformSystemadminBillingcodesController } from "./controllers/healthcarePlatform/systemAdmin/billingCodes/HealthcareplatformSystemadminBillingcodesController";
import { HealthcareplatformSystemadminBillinginvoicesBillingadjustmentsController } from "./controllers/healthcarePlatform/systemAdmin/billingInvoices/billingAdjustments/HealthcareplatformSystemadminBillinginvoicesBillingadjustmentsController";
import { HealthcareplatformOrganizationadminBillinginvoicesBillingadjustmentsController } from "./controllers/healthcarePlatform/organizationAdmin/billingInvoices/billingAdjustments/HealthcareplatformOrganizationadminBillinginvoicesBillingadjustmentsController";
import { HealthcareplatformOrganizationadminBillingdiscountpoliciesController } from "./controllers/healthcarePlatform/organizationAdmin/billingDiscountPolicies/HealthcareplatformOrganizationadminBillingdiscountpoliciesController";
import { HealthcareplatformOrganizationadminBillinginvoicesBillingpaymentplansController } from "./controllers/healthcarePlatform/organizationAdmin/billingInvoices/billingPaymentPlans/HealthcareplatformOrganizationadminBillinginvoicesBillingpaymentplansController";
import { HealthcareplatformOrganizationadminBillinginvoicesBillingpaymentsController } from "./controllers/healthcarePlatform/organizationAdmin/billingInvoices/billingPayments/HealthcareplatformOrganizationadminBillinginvoicesBillingpaymentsController";
import { HealthcareplatformBillingpaymentmethodsController } from "./controllers/healthcarePlatform/billingPaymentMethods/HealthcareplatformBillingpaymentmethodsController";
import { HealthcareplatformOrganizationadminBillingpaymentmethodsController } from "./controllers/healthcarePlatform/organizationAdmin/billingPaymentMethods/HealthcareplatformOrganizationadminBillingpaymentmethodsController";
import { HealthcareplatformOrganizationadminInsurancepoliciesController } from "./controllers/healthcarePlatform/organizationAdmin/insurancePolicies/HealthcareplatformOrganizationadminInsurancepoliciesController";
import { HealthcareplatformOrganizationadminInsurancepoliciesInsuranceeligibilitychecksController } from "./controllers/healthcarePlatform/organizationAdmin/insurancePolicies/insuranceEligibilityChecks/HealthcareplatformOrganizationadminInsurancepoliciesInsuranceeligibilitychecksController";
import { HealthcareplatformSystemadminInsurancepoliciesInsuranceeligibilitychecksController } from "./controllers/healthcarePlatform/systemAdmin/insurancePolicies/insuranceEligibilityChecks/HealthcareplatformSystemadminInsurancepoliciesInsuranceeligibilitychecksController";
import { HealthcareplatformOrganizationadminInsuranceclaimsController } from "./controllers/healthcarePlatform/organizationAdmin/insuranceClaims/HealthcareplatformOrganizationadminInsuranceclaimsController";
import { HealthcareplatformOrganizationadminInsuranceclaimsInsuranceclaimstatusesController } from "./controllers/healthcarePlatform/organizationAdmin/insuranceClaims/insuranceClaimStatuses/HealthcareplatformOrganizationadminInsuranceclaimsInsuranceclaimstatusesController";
import { HealthcareplatformSystemadminFinancialauditlogsController } from "./controllers/healthcarePlatform/systemAdmin/financialAuditLogs/HealthcareplatformSystemadminFinancialauditlogsController";
import { HealthcareplatformOrganizationadminFinancialauditlogsController } from "./controllers/healthcarePlatform/organizationAdmin/financialAuditLogs/HealthcareplatformOrganizationadminFinancialauditlogsController";
import { HealthcareplatformSystemadminInsuranceclaimsInsuranceclaimstatusesController } from "./controllers/healthcarePlatform/systemAdmin/insuranceClaims/insuranceClaimStatuses/HealthcareplatformSystemadminInsuranceclaimsInsuranceclaimstatusesController";
import { HealthcareplatformSystemadminAnalyticsdashboardsController } from "./controllers/healthcarePlatform/systemAdmin/analyticsDashboards/HealthcareplatformSystemadminAnalyticsdashboardsController";
import { HealthcareplatformOrganizationadminAnalyticsdashboardsController } from "./controllers/healthcarePlatform/organizationAdmin/analyticsDashboards/HealthcareplatformOrganizationadminAnalyticsdashboardsController";
import { HealthcareplatformDepartmentheadAnalyticsdashboardsController } from "./controllers/healthcarePlatform/departmentHead/analyticsDashboards/HealthcareplatformDepartmentheadAnalyticsdashboardsController";
import { HealthcareplatformOrganizationadminAnalyticsdashboardsPreferencesController } from "./controllers/healthcarePlatform/organizationAdmin/analyticsDashboards/preferences/HealthcareplatformOrganizationadminAnalyticsdashboardsPreferencesController";
import { HealthcareplatformDepartmentheadAnalyticsdashboardsPreferencesController } from "./controllers/healthcarePlatform/departmentHead/analyticsDashboards/preferences/HealthcareplatformDepartmentheadAnalyticsdashboardsPreferencesController";
import { HealthcareplatformSystemadminAnalyticsdashboardsPreferencesController } from "./controllers/healthcarePlatform/systemAdmin/analyticsDashboards/preferences/HealthcareplatformSystemadminAnalyticsdashboardsPreferencesController";
import { HealthcareplatformMedicaldoctorAnalyticsdashboardsPreferencesController } from "./controllers/healthcarePlatform/medicalDoctor/analyticsDashboards/preferences/HealthcareplatformMedicaldoctorAnalyticsdashboardsPreferencesController";
import { HealthcareplatformNurseAnalyticsdashboardsPreferencesController } from "./controllers/healthcarePlatform/nurse/analyticsDashboards/preferences/HealthcareplatformNurseAnalyticsdashboardsPreferencesController";
import { HealthcareplatformTechnicianAnalyticsdashboardsPreferencesController } from "./controllers/healthcarePlatform/technician/analyticsDashboards/preferences/HealthcareplatformTechnicianAnalyticsdashboardsPreferencesController";
import { HealthcareplatformReceptionistAnalyticsdashboardsPreferencesController } from "./controllers/healthcarePlatform/receptionist/analyticsDashboards/preferences/HealthcareplatformReceptionistAnalyticsdashboardsPreferencesController";
import { HealthcareplatformPatientAnalyticsdashboardsPreferencesController } from "./controllers/healthcarePlatform/patient/analyticsDashboards/preferences/HealthcareplatformPatientAnalyticsdashboardsPreferencesController";
import { HealthcareplatformSystemadminAnalyticsreportsController } from "./controllers/healthcarePlatform/systemAdmin/analyticsReports/HealthcareplatformSystemadminAnalyticsreportsController";
import { HealthcareplatformOrganizationadminAnalyticsreportsController } from "./controllers/healthcarePlatform/organizationAdmin/analyticsReports/HealthcareplatformOrganizationadminAnalyticsreportsController";
import { HealthcareplatformDepartmentheadAnalyticsreportsController } from "./controllers/healthcarePlatform/departmentHead/analyticsReports/HealthcareplatformDepartmentheadAnalyticsreportsController";
import { HealthcareplatformMedicaldoctorAnalyticsreportsController } from "./controllers/healthcarePlatform/medicalDoctor/analyticsReports/HealthcareplatformMedicaldoctorAnalyticsreportsController";
import { HealthcareplatformNurseAnalyticsreportsController } from "./controllers/healthcarePlatform/nurse/analyticsReports/HealthcareplatformNurseAnalyticsreportsController";
import { HealthcareplatformTechnicianAnalyticsreportsController } from "./controllers/healthcarePlatform/technician/analyticsReports/HealthcareplatformTechnicianAnalyticsreportsController";
import { HealthcareplatformReceptionistAnalyticsreportsController } from "./controllers/healthcarePlatform/receptionist/analyticsReports/HealthcareplatformReceptionistAnalyticsreportsController";
import { HealthcareplatformPatientAnalyticsreportsController } from "./controllers/healthcarePlatform/patient/analyticsReports/HealthcareplatformPatientAnalyticsreportsController";
import { HealthcareplatformSystemadminDecisionsupportrulesController } from "./controllers/healthcarePlatform/systemAdmin/decisionSupportRules/HealthcareplatformSystemadminDecisionsupportrulesController";
import { HealthcareplatformOrganizationadminDecisionsupportrulesController } from "./controllers/healthcarePlatform/organizationAdmin/decisionSupportRules/HealthcareplatformOrganizationadminDecisionsupportrulesController";
import { HealthcareplatformSystemadminClinicalalertsController } from "./controllers/healthcarePlatform/systemAdmin/clinicalAlerts/HealthcareplatformSystemadminClinicalalertsController";
import { HealthcareplatformOrganizationadminClinicalalertsController } from "./controllers/healthcarePlatform/organizationAdmin/clinicalAlerts/HealthcareplatformOrganizationadminClinicalalertsController";
import { HealthcareplatformDepartmentheadClinicalalertsController } from "./controllers/healthcarePlatform/departmentHead/clinicalAlerts/HealthcareplatformDepartmentheadClinicalalertsController";
import { HealthcareplatformSystemadminOutcomemetricsController } from "./controllers/healthcarePlatform/systemAdmin/outcomeMetrics/HealthcareplatformSystemadminOutcomemetricsController";
import { HealthcareplatformOrganizationadminOutcomemetricsController } from "./controllers/healthcarePlatform/organizationAdmin/outcomeMetrics/HealthcareplatformOrganizationadminOutcomemetricsController";
import { HealthcareplatformDepartmentheadOutcomemetricsController } from "./controllers/healthcarePlatform/departmentHead/outcomeMetrics/HealthcareplatformDepartmentheadOutcomemetricsController";
import { HealthcareplatformOrganizationadminBenchmarkdefinitionsController } from "./controllers/healthcarePlatform/organizationAdmin/benchmarkDefinitions/HealthcareplatformOrganizationadminBenchmarkdefinitionsController";
import { HealthcareplatformSystemadminBenchmarkdefinitionsController } from "./controllers/healthcarePlatform/systemAdmin/benchmarkDefinitions/HealthcareplatformSystemadminBenchmarkdefinitionsController";
import { HealthcareplatformSystemadminKpisnapshotsController } from "./controllers/healthcarePlatform/systemAdmin/kpiSnapshots/HealthcareplatformSystemadminKpisnapshotsController";
import { HealthcareplatformOrganizationadminKpisnapshotsController } from "./controllers/healthcarePlatform/organizationAdmin/kpiSnapshots/HealthcareplatformOrganizationadminKpisnapshotsController";
import { HealthcareplatformDepartmentheadKpisnapshotsController } from "./controllers/healthcarePlatform/departmentHead/kpiSnapshots/HealthcareplatformDepartmentheadKpisnapshotsController";
import { HealthcareplatformSystemadminExternalemrconnectorsController } from "./controllers/healthcarePlatform/systemAdmin/externalEmrConnectors/HealthcareplatformSystemadminExternalemrconnectorsController";
import { HealthcareplatformOrganizationadminExternalemrconnectorsController } from "./controllers/healthcarePlatform/organizationAdmin/externalEmrConnectors/HealthcareplatformOrganizationadminExternalemrconnectorsController";
import { HealthcareplatformSystemadminLabintegrationsController } from "./controllers/healthcarePlatform/systemAdmin/labIntegrations/HealthcareplatformSystemadminLabintegrationsController";
import { HealthcareplatformOrganizationadminLabintegrationsController } from "./controllers/healthcarePlatform/organizationAdmin/labIntegrations/HealthcareplatformOrganizationadminLabintegrationsController";
import { HealthcareplatformOrganizationadminLabordertransactionsController } from "./controllers/healthcarePlatform/organizationAdmin/labOrderTransactions/HealthcareplatformOrganizationadminLabordertransactionsController";
import { HealthcareplatformOrganizationadminLabresultimportsController } from "./controllers/healthcarePlatform/organizationAdmin/labResultImports/HealthcareplatformOrganizationadminLabresultimportsController";
import { HealthcareplatformOrganizationadminPharmacyintegrationsController } from "./controllers/healthcarePlatform/organizationAdmin/pharmacyIntegrations/HealthcareplatformOrganizationadminPharmacyintegrationsController";
import { HealthcareplatformSystemadminPharmacyintegrationsController } from "./controllers/healthcarePlatform/systemAdmin/pharmacyIntegrations/HealthcareplatformSystemadminPharmacyintegrationsController";
import { HealthcareplatformSystemadminPharmacytransactionsController } from "./controllers/healthcarePlatform/systemAdmin/pharmacyTransactions/HealthcareplatformSystemadminPharmacytransactionsController";
import { HealthcareplatformOrganizationadminPharmacytransactionsController } from "./controllers/healthcarePlatform/organizationAdmin/pharmacyTransactions/HealthcareplatformOrganizationadminPharmacytransactionsController";
import { HealthcareplatformSystemadminInsuranceapiintegrationsController } from "./controllers/healthcarePlatform/systemAdmin/insuranceApiIntegrations/HealthcareplatformSystemadminInsuranceapiintegrationsController";
import { HealthcareplatformOrganizationadminInsuranceapiintegrationsController } from "./controllers/healthcarePlatform/organizationAdmin/insuranceApiIntegrations/HealthcareplatformOrganizationadminInsuranceapiintegrationsController";
import { HealthcareplatformSystemadminDevicedataingestionsController } from "./controllers/healthcarePlatform/systemAdmin/deviceDataIngestions/HealthcareplatformSystemadminDevicedataingestionsController";
import { HealthcareplatformOrganizationadminDevicedataingestionsController } from "./controllers/healthcarePlatform/organizationAdmin/deviceDataIngestions/HealthcareplatformOrganizationadminDevicedataingestionsController";
import { HealthcareplatformSystemadminIntegrationlogsController } from "./controllers/healthcarePlatform/systemAdmin/integrationLogs/HealthcareplatformSystemadminIntegrationlogsController";
import { HealthcareplatformOrganizationadminIntegrationlogsController } from "./controllers/healthcarePlatform/organizationAdmin/integrationLogs/HealthcareplatformOrganizationadminIntegrationlogsController";
import { HealthcareplatformSystemadminComplianceconsentsController } from "./controllers/healthcarePlatform/systemAdmin/complianceConsents/HealthcareplatformSystemadminComplianceconsentsController";
import { HealthcareplatformOrganizationadminComplianceconsentsController } from "./controllers/healthcarePlatform/organizationAdmin/complianceConsents/HealthcareplatformOrganizationadminComplianceconsentsController";
import { HealthcareplatformOrganizationadminComplianceagreementsController } from "./controllers/healthcarePlatform/organizationAdmin/complianceAgreements/HealthcareplatformOrganizationadminComplianceagreementsController";
import { HealthcareplatformSystemadminComplianceagreementsController } from "./controllers/healthcarePlatform/systemAdmin/complianceAgreements/HealthcareplatformSystemadminComplianceagreementsController";
import { HealthcareplatformSystemadminPolicyversionsController } from "./controllers/healthcarePlatform/systemAdmin/policyVersions/HealthcareplatformSystemadminPolicyversionsController";
import { HealthcareplatformOrganizationadminPolicyversionsController } from "./controllers/healthcarePlatform/organizationAdmin/policyVersions/HealthcareplatformOrganizationadminPolicyversionsController";
import { HealthcareplatformSystemadminRiskassessmentsController } from "./controllers/healthcarePlatform/systemAdmin/riskAssessments/HealthcareplatformSystemadminRiskassessmentsController";
import { HealthcareplatformOrganizationadminRiskassessmentsController } from "./controllers/healthcarePlatform/organizationAdmin/riskAssessments/HealthcareplatformOrganizationadminRiskassessmentsController";
import { HealthcareplatformOrganizationadminLegalholdsController } from "./controllers/healthcarePlatform/organizationAdmin/legalHolds/HealthcareplatformOrganizationadminLegalholdsController";
import { HealthcareplatformSystemadminLegalholdsController } from "./controllers/healthcarePlatform/systemAdmin/legalHolds/HealthcareplatformSystemadminLegalholdsController";
import { HealthcareplatformSystemadminCompliancereviewsController } from "./controllers/healthcarePlatform/systemAdmin/complianceReviews/HealthcareplatformSystemadminCompliancereviewsController";
import { HealthcareplatformOrganizationadminCompliancereviewsController } from "./controllers/healthcarePlatform/organizationAdmin/complianceReviews/HealthcareplatformOrganizationadminCompliancereviewsController";
import { HealthcareplatformSystemadminAuditlogsController } from "./controllers/healthcarePlatform/systemAdmin/auditLogs/HealthcareplatformSystemadminAuditlogsController";
import { HealthcareplatformOrganizationadminAuditlogsController } from "./controllers/healthcarePlatform/organizationAdmin/auditLogs/HealthcareplatformOrganizationadminAuditlogsController";
import { HealthcareplatformSystemadminAccesslogsController } from "./controllers/healthcarePlatform/systemAdmin/accessLogs/HealthcareplatformSystemadminAccesslogsController";
import { HealthcareplatformOrganizationadminAccesslogsController } from "./controllers/healthcarePlatform/organizationAdmin/accessLogs/HealthcareplatformOrganizationadminAccesslogsController";
import { HealthcareplatformSystemadminDataexportlogsController } from "./controllers/healthcarePlatform/systemAdmin/dataExportLogs/HealthcareplatformSystemadminDataexportlogsController";
import { HealthcareplatformOrganizationadminDataexportlogsController } from "./controllers/healthcarePlatform/organizationAdmin/dataExportLogs/HealthcareplatformOrganizationadminDataexportlogsController";
import { HealthcareplatformSystemadminSecurityincidentsController } from "./controllers/healthcarePlatform/systemAdmin/securityIncidents/HealthcareplatformSystemadminSecurityincidentsController";
import { HealthcareplatformOrganizationadminSecurityincidentsController } from "./controllers/healthcarePlatform/organizationAdmin/securityIncidents/HealthcareplatformOrganizationadminSecurityincidentsController";
import { HealthcareplatformSystemadminEmergencyaccessoverridesController } from "./controllers/healthcarePlatform/systemAdmin/emergencyAccessOverrides/HealthcareplatformSystemadminEmergencyaccessoverridesController";
import { HealthcareplatformOrganizationadminEmergencyaccessoverridesController } from "./controllers/healthcarePlatform/organizationAdmin/emergencyAccessOverrides/HealthcareplatformOrganizationadminEmergencyaccessoverridesController";
import { HealthcareplatformSystemadminAuditlogarchivesController } from "./controllers/healthcarePlatform/systemAdmin/auditLogArchives/HealthcareplatformSystemadminAuditlogarchivesController";
import { HealthcareplatformOrganizationadminAuditlogarchivesController } from "./controllers/healthcarePlatform/organizationAdmin/auditLogArchives/HealthcareplatformOrganizationadminAuditlogarchivesController";
import { HealthcareplatformSystemadminNotificationsController } from "./controllers/healthcarePlatform/systemAdmin/notifications/HealthcareplatformSystemadminNotificationsController";
import { HealthcareplatformOrganizationadminNotificationsController } from "./controllers/healthcarePlatform/organizationAdmin/notifications/HealthcareplatformOrganizationadminNotificationsController";
import { HealthcareplatformDepartmentheadNotificationsController } from "./controllers/healthcarePlatform/departmentHead/notifications/HealthcareplatformDepartmentheadNotificationsController";
import { HealthcareplatformMedicaldoctorNotificationsController } from "./controllers/healthcarePlatform/medicalDoctor/notifications/HealthcareplatformMedicaldoctorNotificationsController";
import { HealthcareplatformNurseNotificationsController } from "./controllers/healthcarePlatform/nurse/notifications/HealthcareplatformNurseNotificationsController";
import { HealthcareplatformTechnicianNotificationsController } from "./controllers/healthcarePlatform/technician/notifications/HealthcareplatformTechnicianNotificationsController";
import { HealthcareplatformReceptionistNotificationsController } from "./controllers/healthcarePlatform/receptionist/notifications/HealthcareplatformReceptionistNotificationsController";
import { HealthcareplatformPatientNotificationsController } from "./controllers/healthcarePlatform/patient/notifications/HealthcareplatformPatientNotificationsController";
import { HealthcareplatformSystemadminNotificationpreferencesController } from "./controllers/healthcarePlatform/systemAdmin/notificationPreferences/HealthcareplatformSystemadminNotificationpreferencesController";
import { HealthcareplatformOrganizationadminNotificationpreferencesController } from "./controllers/healthcarePlatform/organizationAdmin/notificationPreferences/HealthcareplatformOrganizationadminNotificationpreferencesController";
import { HealthcareplatformPatientNotificationpreferencesController } from "./controllers/healthcarePlatform/patient/notificationPreferences/HealthcareplatformPatientNotificationpreferencesController";
import { HealthcareplatformOrganizationadminNotificationhistoryController } from "./controllers/healthcarePlatform/organizationAdmin/notificationHistory/HealthcareplatformOrganizationadminNotificationhistoryController";
import { HealthcareplatformPatientNotificationhistoryController } from "./controllers/healthcarePlatform/patient/notificationHistory/HealthcareplatformPatientNotificationhistoryController";
import { HealthcareplatformSystemadminEscalationeventsController } from "./controllers/healthcarePlatform/systemAdmin/escalationEvents/HealthcareplatformSystemadminEscalationeventsController";
import { HealthcareplatformOrganizationadminEscalationeventsController } from "./controllers/healthcarePlatform/organizationAdmin/escalationEvents/HealthcareplatformOrganizationadminEscalationeventsController";
import { HealthcareplatformSystemadminRemindersController } from "./controllers/healthcarePlatform/systemAdmin/reminders/HealthcareplatformSystemadminRemindersController";
import { HealthcareplatformOrganizationadminRemindersController } from "./controllers/healthcarePlatform/organizationAdmin/reminders/HealthcareplatformOrganizationadminRemindersController";
import { HealthcareplatformDepartmentheadRemindersController } from "./controllers/healthcarePlatform/departmentHead/reminders/HealthcareplatformDepartmentheadRemindersController";
import { HealthcareplatformMedicaldoctorRemindersController } from "./controllers/healthcarePlatform/medicalDoctor/reminders/HealthcareplatformMedicaldoctorRemindersController";
import { HealthcareplatformNurseRemindersController } from "./controllers/healthcarePlatform/nurse/reminders/HealthcareplatformNurseRemindersController";
import { HealthcareplatformTechnicianRemindersController } from "./controllers/healthcarePlatform/technician/reminders/HealthcareplatformTechnicianRemindersController";
import { HealthcareplatformReceptionistRemindersController } from "./controllers/healthcarePlatform/receptionist/reminders/HealthcareplatformReceptionistRemindersController";
import { HealthcareplatformPatientRemindersController } from "./controllers/healthcarePlatform/patient/reminders/HealthcareplatformPatientRemindersController";

@Module({
  controllers: [
    AuthSystemadminController,
    AuthOrganizationadminController,
    AuthDepartmentheadController,
    AuthMedicaldoctorController,
    AuthNurseController,
    AuthTechnicianController,
    AuthReceptionistController,
    AuthPatientController,
    HealthcareplatformSystemadminOrganizationsController,
    HealthcareplatformOrganizationadminOrganizationsDepartmentsController,
    HealthcareplatformDepartmentheadOrganizationsDepartmentsController,
    HealthcareplatformSystemadminRolesController,
    HealthcareplatformOrganizationadminRolesController,
    HealthcareplatformSystemadminPermissionsController,
    HealthcareplatformSystemadminOrgdepartmentassignmentsController,
    HealthcareplatformOrganizationadminOrgdepartmentassignmentsController,
    HealthcareplatformSystemadminUserorgassignmentsController,
    HealthcareplatformOrganizationadminUserorgassignmentsController,
    HealthcareplatformSystemadminConfigurationController,
    HealthcareplatformOrganizationadminConfigurationController,
    HealthcareplatformSystemadminLocalesettingsController,
    HealthcareplatformOrganizationadminLocalesettingsController,
    HealthcareplatformSystemadminSystemadminsController,
    HealthcareplatformSystemadminOrganizationadminsController,
    HealthcareplatformOrganizationadminOrganizationadminsController,
    HealthcareplatformSystemadminDepartmentheadsController,
    HealthcareplatformOrganizationadminDepartmentheadsController,
    HealthcareplatformOrganizationadminMedicaldoctorsController,
    HealthcareplatformSystemadminMedicaldoctorsController,
    HealthcareplatformOrganizationadminNursesController,
    HealthcareplatformDepartmentheadNursesController,
    HealthcareplatformSystemadminNursesController,
    HealthcareplatformSystemadminTechniciansController,
    HealthcareplatformOrganizationadminTechniciansController,
    HealthcareplatformSystemadminReceptionistsController,
    HealthcareplatformOrganizationadminReceptionistsController,
    HealthcareplatformOrganizationadminPatientsController,
    HealthcareplatformMedicaldoctorPatientsController,
    HealthcareplatformNursePatientsController,
    HealthcareplatformReceptionistPatientsController,
    HealthcareplatformPatientPatientsController,
    HealthcareplatformSystemadminUserauthenticationsController,
    HealthcareplatformOrganizationadminUserauthenticationsController,
    HealthcareplatformSystemadminAuthsessionsController,
    HealthcareplatformSystemadminUsermfafactorsController,
    HealthcareplatformOrganizationadminUsermfafactorsController,
    HealthcareplatformSystemadminUsercredentialsController,
    HealthcareplatformOrganizationadminUsercredentialsController,
    HealthcareplatformSystemadminUserlicenseverificationsController,
    HealthcareplatformOrganizationadminUserlicenseverificationsController,
    HealthcareplatformOrganizationadminPatientrecordsController,
    HealthcareplatformMedicaldoctorPatientrecordsController,
    HealthcareplatformNursePatientrecordsController,
    HealthcareplatformDepartmentheadPatientrecordsController,
    HealthcareplatformSystemadminPatientrecordsController,
    HealthcareplatformReceptionistPatientrecordsController,
    HealthcareplatformMedicaldoctorPatientrecordsEncountersController,
    HealthcareplatformNursePatientrecordsEncountersController,
    HealthcareplatformOrganizationadminPatientrecordsEncountersController,
    HealthcareplatformDepartmentheadPatientrecordsEncountersController,
    HealthcareplatformSystemadminPatientrecordsEncountersEhrversionsController,
    HealthcareplatformMedicaldoctorPatientrecordsEncountersEhrversionsController,
    HealthcareplatformNursePatientrecordsEncountersEhrversionsController,
    HealthcareplatformDepartmentheadPatientrecordsEncountersEhrversionsController,
    HealthcareplatformDepartmentheadPatientrecordsRecordamendmentsController,
    HealthcareplatformMedicaldoctorPatientrecordsRecordamendmentsController,
    HealthcareplatformNursePatientrecordsRecordamendmentsController,
    HealthcareplatformOrganizationadminPatientrecordsRecordamendmentsController,
    HealthcareplatformSystemadminPatientrecordsRecordamendmentsController,
    HealthcareplatformSystemadminPatientrecordsRecordaudittrailsController,
    HealthcareplatformSystemadminPatientrecordsMedicalimagesController,
    HealthcareplatformMedicaldoctorPatientrecordsMedicalimagesController,
    HealthcareplatformNursePatientrecordsMedicalimagesController,
    HealthcareplatformTechnicianPatientrecordsMedicalimagesController,
    HealthcareplatformPatientPatientrecordsMedicalimagesController,
    HealthcareplatformMedicaldoctorPatientrecordsEncountersLabresultsController,
    HealthcareplatformNursePatientrecordsEncountersLabresultsController,
    HealthcareplatformTechnicianPatientrecordsEncountersLabresultsController,
    HealthcareplatformDepartmentheadPatientrecordsEncountersLabresultsController,
    HealthcareplatformOrganizationadminPatientrecordsEncountersLabresultsController,
    HealthcareplatformMedicaldoctorPatientrecordsEncountersVitalsController,
    HealthcareplatformNursePatientrecordsEncountersVitalsController,
    HealthcareplatformDepartmentheadPatientrecordsEncountersVitalsController,
    HealthcareplatformSystemadminAppointmentsController,
    HealthcareplatformOrganizationadminAppointmentsController,
    HealthcareplatformDepartmentheadAppointmentsController,
    HealthcareplatformMedicaldoctorAppointmentsController,
    HealthcareplatformNurseAppointmentsController,
    HealthcareplatformTechnicianAppointmentsController,
    HealthcareplatformReceptionistAppointmentsController,
    HealthcareplatformPatientAppointmentsController,
    HealthcareplatformReceptionistAppointmentsRemindersController,
    HealthcareplatformOrganizationadminAppointmentsRemindersController,
    HealthcareplatformDepartmentheadAppointmentsRemindersController,
    HealthcareplatformMedicaldoctorAppointmentsRemindersController,
    HealthcareplatformSystemadminAppointmentsRemindersController,
    HealthcareplatformNurseAppointmentsRemindersController,
    HealthcareplatformTechnicianAppointmentsRemindersController,
    HealthcareplatformPatientAppointmentsRemindersController,
    HealthcareplatformSystemadminAppointmentsWaitlistsController,
    HealthcareplatformOrganizationadminAppointmentsWaitlistsController,
    HealthcareplatformDepartmentheadAppointmentsWaitlistsController,
    HealthcareplatformMedicaldoctorAppointmentsWaitlistsController,
    HealthcareplatformNurseAppointmentsWaitlistsController,
    HealthcareplatformTechnicianAppointmentsWaitlistsController,
    HealthcareplatformReceptionistAppointmentsWaitlistsController,
    HealthcareplatformPatientAppointmentsWaitlistsController,
    HealthcareplatformReceptionistAppointmentstatusesController,
    HealthcareplatformOrganizationadminAppointmentstatusesController,
    HealthcareplatformSystemadminAppointmentstatusesController,
    HealthcareplatformSystemadminResourceschedulesController,
    HealthcareplatformOrganizationadminResourceschedulesController,
    HealthcareplatformOrganizationadminRoomreservationsController,
    HealthcareplatformDepartmentheadRoomreservationsController,
    HealthcareplatformReceptionistRoomreservationsController,
    HealthcareplatformSystemadminRoomreservationsController,
    HealthcareplatformSystemadminEquipmentreservationsController,
    HealthcareplatformOrganizationadminEquipmentreservationsController,
    HealthcareplatformDepartmentheadEquipmentreservationsController,
    HealthcareplatformOrganizationadminCalendarsettingsController,
    HealthcareplatformOrganizationadminTelemedicinesessionsController,
    HealthcareplatformMedicaldoctorTelemedicinesessionsController,
    HealthcareplatformSystemadminTelemedicinesessionsController,
    HealthcareplatformSystemadminBillinginvoicesController,
    HealthcareplatformOrganizationadminBillinginvoicesController,
    HealthcareplatformDepartmentheadBillinginvoicesController,
    HealthcareplatformPatientBillinginvoicesController,
    HealthcareplatformOrganizationadminBillinginvoicesBillingitemsController,
    HealthcareplatformDepartmentheadBillinginvoicesBillingitemsController,
    HealthcareplatformOrganizationadminBillingcodesController,
    HealthcareplatformSystemadminBillingcodesController,
    HealthcareplatformSystemadminBillinginvoicesBillingadjustmentsController,
    HealthcareplatformOrganizationadminBillinginvoicesBillingadjustmentsController,
    HealthcareplatformOrganizationadminBillingdiscountpoliciesController,
    HealthcareplatformOrganizationadminBillinginvoicesBillingpaymentplansController,
    HealthcareplatformOrganizationadminBillinginvoicesBillingpaymentsController,
    HealthcareplatformBillingpaymentmethodsController,
    HealthcareplatformOrganizationadminBillingpaymentmethodsController,
    HealthcareplatformOrganizationadminInsurancepoliciesController,
    HealthcareplatformOrganizationadminInsurancepoliciesInsuranceeligibilitychecksController,
    HealthcareplatformSystemadminInsurancepoliciesInsuranceeligibilitychecksController,
    HealthcareplatformOrganizationadminInsuranceclaimsController,
    HealthcareplatformOrganizationadminInsuranceclaimsInsuranceclaimstatusesController,
    HealthcareplatformSystemadminFinancialauditlogsController,
    HealthcareplatformOrganizationadminFinancialauditlogsController,
    HealthcareplatformSystemadminInsuranceclaimsInsuranceclaimstatusesController,
    HealthcareplatformSystemadminAnalyticsdashboardsController,
    HealthcareplatformOrganizationadminAnalyticsdashboardsController,
    HealthcareplatformDepartmentheadAnalyticsdashboardsController,
    HealthcareplatformOrganizationadminAnalyticsdashboardsPreferencesController,
    HealthcareplatformDepartmentheadAnalyticsdashboardsPreferencesController,
    HealthcareplatformSystemadminAnalyticsdashboardsPreferencesController,
    HealthcareplatformMedicaldoctorAnalyticsdashboardsPreferencesController,
    HealthcareplatformNurseAnalyticsdashboardsPreferencesController,
    HealthcareplatformTechnicianAnalyticsdashboardsPreferencesController,
    HealthcareplatformReceptionistAnalyticsdashboardsPreferencesController,
    HealthcareplatformPatientAnalyticsdashboardsPreferencesController,
    HealthcareplatformSystemadminAnalyticsreportsController,
    HealthcareplatformOrganizationadminAnalyticsreportsController,
    HealthcareplatformDepartmentheadAnalyticsreportsController,
    HealthcareplatformMedicaldoctorAnalyticsreportsController,
    HealthcareplatformNurseAnalyticsreportsController,
    HealthcareplatformTechnicianAnalyticsreportsController,
    HealthcareplatformReceptionistAnalyticsreportsController,
    HealthcareplatformPatientAnalyticsreportsController,
    HealthcareplatformSystemadminDecisionsupportrulesController,
    HealthcareplatformOrganizationadminDecisionsupportrulesController,
    HealthcareplatformSystemadminClinicalalertsController,
    HealthcareplatformOrganizationadminClinicalalertsController,
    HealthcareplatformDepartmentheadClinicalalertsController,
    HealthcareplatformSystemadminOutcomemetricsController,
    HealthcareplatformOrganizationadminOutcomemetricsController,
    HealthcareplatformDepartmentheadOutcomemetricsController,
    HealthcareplatformOrganizationadminBenchmarkdefinitionsController,
    HealthcareplatformSystemadminBenchmarkdefinitionsController,
    HealthcareplatformSystemadminKpisnapshotsController,
    HealthcareplatformOrganizationadminKpisnapshotsController,
    HealthcareplatformDepartmentheadKpisnapshotsController,
    HealthcareplatformSystemadminExternalemrconnectorsController,
    HealthcareplatformOrganizationadminExternalemrconnectorsController,
    HealthcareplatformSystemadminLabintegrationsController,
    HealthcareplatformOrganizationadminLabintegrationsController,
    HealthcareplatformOrganizationadminLabordertransactionsController,
    HealthcareplatformOrganizationadminLabresultimportsController,
    HealthcareplatformOrganizationadminPharmacyintegrationsController,
    HealthcareplatformSystemadminPharmacyintegrationsController,
    HealthcareplatformSystemadminPharmacytransactionsController,
    HealthcareplatformOrganizationadminPharmacytransactionsController,
    HealthcareplatformSystemadminInsuranceapiintegrationsController,
    HealthcareplatformOrganizationadminInsuranceapiintegrationsController,
    HealthcareplatformSystemadminDevicedataingestionsController,
    HealthcareplatformOrganizationadminDevicedataingestionsController,
    HealthcareplatformSystemadminIntegrationlogsController,
    HealthcareplatformOrganizationadminIntegrationlogsController,
    HealthcareplatformSystemadminComplianceconsentsController,
    HealthcareplatformOrganizationadminComplianceconsentsController,
    HealthcareplatformOrganizationadminComplianceagreementsController,
    HealthcareplatformSystemadminComplianceagreementsController,
    HealthcareplatformSystemadminPolicyversionsController,
    HealthcareplatformOrganizationadminPolicyversionsController,
    HealthcareplatformSystemadminRiskassessmentsController,
    HealthcareplatformOrganizationadminRiskassessmentsController,
    HealthcareplatformOrganizationadminLegalholdsController,
    HealthcareplatformSystemadminLegalholdsController,
    HealthcareplatformSystemadminCompliancereviewsController,
    HealthcareplatformOrganizationadminCompliancereviewsController,
    HealthcareplatformSystemadminAuditlogsController,
    HealthcareplatformOrganizationadminAuditlogsController,
    HealthcareplatformSystemadminAccesslogsController,
    HealthcareplatformOrganizationadminAccesslogsController,
    HealthcareplatformSystemadminDataexportlogsController,
    HealthcareplatformOrganizationadminDataexportlogsController,
    HealthcareplatformSystemadminSecurityincidentsController,
    HealthcareplatformOrganizationadminSecurityincidentsController,
    HealthcareplatformSystemadminEmergencyaccessoverridesController,
    HealthcareplatformOrganizationadminEmergencyaccessoverridesController,
    HealthcareplatformSystemadminAuditlogarchivesController,
    HealthcareplatformOrganizationadminAuditlogarchivesController,
    HealthcareplatformSystemadminNotificationsController,
    HealthcareplatformOrganizationadminNotificationsController,
    HealthcareplatformDepartmentheadNotificationsController,
    HealthcareplatformMedicaldoctorNotificationsController,
    HealthcareplatformNurseNotificationsController,
    HealthcareplatformTechnicianNotificationsController,
    HealthcareplatformReceptionistNotificationsController,
    HealthcareplatformPatientNotificationsController,
    HealthcareplatformSystemadminNotificationpreferencesController,
    HealthcareplatformOrganizationadminNotificationpreferencesController,
    HealthcareplatformPatientNotificationpreferencesController,
    HealthcareplatformOrganizationadminNotificationhistoryController,
    HealthcareplatformPatientNotificationhistoryController,
    HealthcareplatformSystemadminEscalationeventsController,
    HealthcareplatformOrganizationadminEscalationeventsController,
    HealthcareplatformSystemadminRemindersController,
    HealthcareplatformOrganizationadminRemindersController,
    HealthcareplatformDepartmentheadRemindersController,
    HealthcareplatformMedicaldoctorRemindersController,
    HealthcareplatformNurseRemindersController,
    HealthcareplatformTechnicianRemindersController,
    HealthcareplatformReceptionistRemindersController,
    HealthcareplatformPatientRemindersController,
  ],
})
export class MyModule {}
