import { tags } from "typia";

/**
 * Analytics data showing learning gap statistics per student and subject
 * category.
 *
 * This entity highlights underperformed areas in study tasks, linked to
 * students and subject categories to assist targeted improvements and
 * visualization.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IStudyPlannerLearningGapCharts = {
  /** Unique identifier of the learning gap chart record. */
  id: string & tags.Format<"uuid">;

  /** Unique identifier of the student. */
  student_id: string & tags.Format<"uuid">;

  /** Unique identifier of the subject category. */
  subject_category_id: string & tags.Format<"uuid">;

  /** Quantified measure of the learning gap for the subject category. */
  gap_metric: number;

  /** Record creation timestamp. */
  created_at: string & tags.Format<"date-time">;

  /** Record last update timestamp. */
  updated_at: string & tags.Format<"date-time">;
};
export namespace IStudyPlannerLearningGapCharts {
  /** Request object for searching and filtering learning gap charts. */
  export type IRequest = {
    /** Filter by student unique identifier. Use null to ignore this filter. */
    student_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by subject category unique identifier. Use null to ignore this
     * filter.
     */
    subject_category_id?: (string & tags.Format<"uuid">) | null | undefined;

    /** Current page number for pagination. */
    page?: number | null | undefined;

    /** Limit of records per page. */
    limit?: number | null | undefined;

    /** Sort records by created or updated timestamp. */
    sortBy?: "created_at" | "updated_at" | null | undefined;

    /** Sort order - ascending or descending. */
    order?: "asc" | "desc" | null | undefined;
  };
}
