import { tags } from "typia";

/**
 * Full record for a tenant/organization in the healthcare platform. Used as the
 * top-level multi-tenant partition and compliance audit anchor for all
 * associated records.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IHealthcarePlatformOrganization = {
  /** Primary Key. Globally unique identifier (UUID) for the organization. */
  id: string & tags.Format<"uuid">;

  /**
   * Unique business code for the organization. Used internally for technical
   * and business mapping.
   */
  code: string;

  /** Official organization name for display and legal documentation. */
  name: string;

  /**
   * Current operational and business status of the organization (e.g.,
   * active, suspended, pending, archived, etc.).
   */
  status: string;

  /** Timestamp (ISO 8601 UTC) when the organization was created in the system. */
  created_at: string & tags.Format<"date-time">;

  /** Timestamp (ISO 8601 UTC) when the record was last updated. */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft delete timestamp for archival/compliance retention. Null if
   * organization is active and visible.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IHealthcarePlatformOrganization {
  /**
   * Request type for filtering, searching, and paginating organizations in
   * index/search APIs. All fields are optional for flexible advanced search.
   * Pagination controls are typically required for patch methods.
   */
  export type IRequest = {
    /** Business/technical organization code filter. */
    code?: string | undefined;

    /** Filter by partial or fuzzy match for organization name. */
    name?: string | undefined;

    /** Filter for status (active, pending, archived, etc). */
    status?: string | undefined;

    /** Include only organizations created at or after this ISO8601 date. */
    created_at_from?: (string & tags.Format<"date-time">) | undefined;

    /** Include only organizations created before this ISO8601 date. */
    created_at_to?: (string & tags.Format<"date-time">) | undefined;

    /** Page number for pagination (1-based). */
    page?: (number & tags.Type<"int32">) | undefined;

    /** Page size limit for results; typically 10, 50, 100, etc. */
    limit?: (number & tags.Type<"int32">) | undefined;
  };

  /**
   * Payload for creation of a new healthcare organization entity. All fields
   * are required for onboarding a new organization.
   */
  export type ICreate = {
    /**
     * Unique business code for the organization. Required; used to map org
     * in internal and external systems.
     */
    code: string;

    /**
     * Legal display name for the organization. Required for contract,
     * display, and external documentation.
     */
    name: string;

    /**
     * Initial operational status of the organization. Usually 'active' or
     * 'pending'; must match allowed values for org onboarding.
     */
    status: string;
  };

  /**
   * Fields for updating healthcare organization records. All fields are
   * optional; any provided property will be updated on the target
   * organization.
   */
  export type IUpdate = {
    /**
     * Business code (unique within the healthcare platform) to update; must
     * satisfy organization code business rules.
     */
    code?: string | undefined;

    /**
     * Organization display/legal name to be updated. Required for legal
     * documentation if changed.
     */
    name?: string | undefined;

    /**
     * Updated status; controls visibility and operational capacity (must
     * match allowed values for the business context).
     */
    status?: string | undefined;
  };

  /**
   * Summary object for organization list/search view. Used in paginated
   * result sets and dashboards. All fields are fixed per schema.
   */
  export type ISummary = {
    /** Unique UUID primary key for the organization. */
    id: string & tags.Format<"uuid">;

    /**
     * Unique business code for cross-system mapping, as seen in onboarding
     * or technical documentation.
     */
    code: string;

    /**
     * Organization's legal or business name used for display, compliance,
     * and notifications.
     */
    name: string;

    /**
     * Current operational status of the organization (active, suspended,
     * pending, archived, etc).
     */
    status: string;

    /**
     * Timestamp at which the organization was registered/created (ISO8601
     * format).
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Timestamp at which the organization was last modified (ISO8601
     * format).
     */
    updated_at: string & tags.Format<"date-time">;
  };
}
