import { IPage } from "./IPage";
import { IHealthcarePlatformInsurancePolicy } from "./IHealthcarePlatformInsurancePolicy";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIHealthcarePlatformInsurancePolicy = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: IHealthcarePlatformInsurancePolicy[];
};
