import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody } from "@nestia/core";
import typia from "typia";

import { ITravelRecordMember } from "../../../../../../api/structures/ITravelRecordMember";

@Controller("/auth/member/email/verify/confirm")
export class AuthMemberEmailVerifyConfirmController {
  /**
   * Confirm email verification for member user.
   *
   * Confirm email verification for TravelRecord member user by providing the
   * verification token. Updates member's email verification status.
   *
   * Ensures valid token usage and prevents spoofing.
   *
   * Related operations: sendEmailVerification for token dispatch.
   *
   * @param connection
   * @param body Email verification confirmation token.
   * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
   */
  @TypedRoute.Post()
  public async verifyEmailConfirm(
    @TypedBody()
    body: ITravelRecordMember.IVerifyConfirm,
  ): Promise<ITravelRecordMember.IResult> {
    body;
    return typia.random<ITravelRecordMember.IResult>();
  }
}
