import { tags } from "typia";

/**
 * Job Group entity representing the highest-level job classification in the
 * organizational hierarchy.
 *
 * It includes identifying properties such as unique code and name, and may
 * contain descriptive information for HR and administrative purposes.
 *
 * Timestamps for creation and update are recorded for audit and change
 * tracking.
 *
 * This entity is a fundamental part of the job hierarchy management in the Job
 * Performance Evaluation service.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IJobPerformanceEvalJobGroup = {
  /**
   * Unique code identifying the job group.
   *
   * This property represents the unique identifier code for the job group,
   * used throughout the organizational hierarchy to categorize broad job
   * families. It is a required string value expected to uniquely represent
   * each job group in the system.
   */
  code: string;

  /**
   * Name of the job group.
   *
   * The display name of the job group used in user interfaces and reports. It
   * is a required string field that must accurately reflect the job family
   * name.
   */
  name: string;

  /**
   * Detailed description of the job group.
   *
   * This optional field provides additional context or explanations regarding
   * the job group. It may include organizational notes or relevant
   * information to further describe the group. This field can be null if no
   * description is provided.
   */
  description?: string | null | undefined;

  /**
   * Record creation timestamp.
   *
   * ISO 8601 formatted date-time string indicating when this record was
   * created. This is a read-only field managed by the system.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Record last update timestamp.
   *
   * ISO 8601 formatted date-time string indicating the last time this record
   * was updated. This is a read-only timestamp maintained by the system.
   */
  updated_at: string & tags.Format<"date-time">;
};
export namespace IJobPerformanceEvalJobGroup {
  /** Request type to create a new job group. */
  export type ICreate = {
    /**
     * Unique code identifying the job group.
     *
     * Required field for creating a new job group. Must be unique in the
     * system.
     */
    code: string;

    /**
     * Name of the job group.
     *
     * Required friendly name of the job group.
     */
    name: string;

    /**
     * Detailed description of the job group.
     *
     * Optional descriptive text about this job group.
     */
    description?: string | null | undefined;
  };

  /** Request type to update an existing job group. */
  export type IUpdate = {
    /**
     * Unique code identifying the job group.
     *
     * Optional field. Updating code must maintain uniqueness.
     */
    code?: string | null | undefined;

    /**
     * Name of the job group.
     *
     * Optional field. Represents the display name.
     */
    name?: string | null | undefined;

    /**
     * Detailed description of the job group.
     *
     * Optional descriptive text.
     */
    description?: string | null | undefined;
  };
}
