/**
 * Enumeration for valid mood types in the Mood Diary app. Values correspond to
 * the business-mandated fixed set: happy, sad, anxious, excited, angry, calm,
 * stressed, tired. This enum should be used everywhere a mood_type appears,
 * ensuring all business validation and logic constraints are enforced at the
 * type level. Mood types outside this set are never permitted in requests or
 * responses.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type EMoodType =
  | "happy"
  | "sad"
  | "anxious"
  | "excited"
  | "angry"
  | "calm"
  | "stressed"
  | "tired";
