import { tags } from "typia";

/**
 * Metadata for a resume file uploaded/attached to an applicant's resume. All
 * fields are as defined in the ats_recruitment_resume_files Prisma model,
 * including original filename, storage URI, extension, file size, upload
 * timestamp, and (if applicable) soft-delete time.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IAtsRecruitmentResumeFile = {
  /** Primary Key. Unique identifier (UUID) for the resume file record. */
  id: string & tags.Format<"uuid">;

  /** Foreign key. Resume this file is attached to. */
  ats_recruitment_resume_id: string & tags.Format<"uuid">;

  /** Original uploaded filename. */
  original_filename: string;

  /** Permanent URI/location of the file in storage. */
  file_storage_uri: string;

  /** File extension (e.g., pdf, docx). */
  file_ext: string;

  /** File size in bytes. */
  file_size: number & tags.Type<"int32">;

  /** Timestamp the file was uploaded. */
  uploaded_at: string & tags.Format<"date-time">;

  /** Timestamp of soft deletion. Nullable. If present, file is deleted. */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IAtsRecruitmentResumeFile {
  /**
   * Payload for creating/uploading a new resume file
   * (ats_recruitment_resume_files). Fields are required for uploading:
   * original filename, file storage URI, file extension, and file size. These
   * are mapped directly from file upload handler and used to create the
   * resume file record.
   */
  export type ICreate = {
    /** Original uploaded file name. */
    original_filename: string;

    /** Permanent URI/location for the file (object storage URL, etc). */
    file_storage_uri: string;

    /** File extension (e.g., pdf, docx). */
    file_ext: string;

    /** File size in bytes. */
    file_size: number & tags.Type<"int32">;
  };

  /**
   * Updates descriptive metadata (but not binary content) for a previously
   * uploaded applicant resume file. Only permitted fields are original
   * filename, extension, and size. File content changes require file upload
   * endpoint. Based on ats_recruitment_resume_files Prisma model.
   */
  export type IUpdate = {
    /**
     * The new file name to display or reference for the uploaded resume
     * file. Used for display or search after the file is updated.
     * Reference: ats_recruitment_resume_files.original_filename
     */
    original_filename?: string | undefined;

    /**
     * Updated file extension for the resume file, e.g., "pdf", "docx". Used
     * if changing the file or correcting file type information. Reference:
     * ats_recruitment_resume_files.file_ext
     */
    file_ext?: string | undefined;

    /**
     * The size of the resume file in bytes after update, e.g., adjusted
     * after replacement or correction. Reference:
     * ats_recruitment_resume_files.file_size
     */
    file_size?: (number & tags.Type<"int32">) | undefined;
  };
}
