import { IPage } from "./IPage";
import { ISubscriptionRenewalGuardianUser } from "./ISubscriptionRenewalGuardianUser";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageISubscriptionRenewalGuardianUser = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ISubscriptionRenewalGuardianUser[];
};
