import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IAtsRecruitmentCodingTest } from "../../../../structures/IAtsRecruitmentCodingTest";
import { IPageIAtsRecruitmentCodingTest } from "../../../../structures/IPageIAtsRecruitmentCodingTest";
export * as submissions from "./submissions/index";
export * as results from "./results/index";
export * as externalLogs from "./externalLogs/index";

/**
 * Creates a coding test assignment for an application
 * (ats_recruitment_coding_tests table).
 *
 * This operation enables HR recruiters to create (assign) a new coding test for
 * a specific applicant, linked to a job application. The coding test record
 * tracks the application, applicant, HR recruiter who assigned the test, the
 * test provider (internal platform or an external provider such as Programmers
 * or CodeSignal), the provider's reference ID or URL, the scheduled and
 * deadline times, and the initial status.
 *
 * The coding test creation may trigger notifications to the applicant, as well
 * as setup of external service communication if using third-party platforms,
 * with proper callbacks enabled. All details of the test, such as provider,
 * test URL, delivery, and status, are maintained for later review and audit.
 * Scheduling rules, such as not allowing duplicate assignments for the same
 * application and applicant, are enforced as per business logic.
 *
 * The operation will return the full created coding test record including IDs,
 * provider, scheduling, and linkage fields. Authorization is required: only HR
 * recruiters or system administrators may perform this operation. Errors may
 * occur if referenced application or applicant does not exist, or if business
 * rules (e.g., duplicate test assignments or invalid schedule) are violated.
 *
 * @param props.connection
 * @param props.body Information required to create a coding test assignment for
 *   an application, including links to application, applicant, HR recruiter,
 *   test provider, scheduling details, and test meta.
 * @path /atsRecruitment/systemAdmin/codingTests
 * @accessor api.functional.atsRecruitment.systemAdmin.codingTests.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Information required to create a coding test assignment for an
     * application, including links to application, applicant, HR recruiter,
     * test provider, scheduling details, and test meta.
     */
    body: IAtsRecruitmentCodingTest.ICreate;
  };
  export type Body = IAtsRecruitmentCodingTest.ICreate;
  export type Response = IAtsRecruitmentCodingTest;

  export const METADATA = {
    method: "POST",
    path: "/atsRecruitment/systemAdmin/codingTests",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/atsRecruitment/systemAdmin/codingTests";
  export const random = (): IAtsRecruitmentCodingTest =>
    typia.random<IAtsRecruitmentCodingTest>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Search and retrieve a filtered, paginated list of coding test assignments and
 * progress.
 *
 * Retrieves a paginated collection of coding test assigments from
 * ats_recruitment_coding_tests, supporting advanced filter criteria such as
 * applicant, job posting, status (scheduled, in progress, completed, failed),
 * delivery channel (internal or 3rd-party), scheduled/delivery dates, and
 * provider-specific IDs. It is primarily used by HR and technical reviewers to
 * monitor applicant assessment pipeline progress and by system admins for
 * compliance oversight.
 *
 * Integration with related tables (applications, applicants,
 * submission/results/feedback) enables rich operational dashboarding, while
 * indices on status, applicant, and provider allow for efficient processing
 * even with a high volume of tests.
 *
 * Authorization distinguishes that HR recruiters can only see tests related to
 * their postings, tech reviewers are limited to their assignments, and system
 * admins may see all entries. Each record may summarize the test state, links
 * to test or review, and primary metadata needed for next action. Large
 * datasets are returned in a paginated form.
 *
 * @param props.connection
 * @param props.body Complex filtering parameters and pagination controls for
 *   coding test search
 * @path /atsRecruitment/systemAdmin/codingTests
 * @accessor api.functional.atsRecruitment.systemAdmin.codingTests.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Complex filtering parameters and pagination controls for coding test
     * search
     */
    body: IAtsRecruitmentCodingTest.IRequest;
  };
  export type Body = IAtsRecruitmentCodingTest.IRequest;
  export type Response = IPageIAtsRecruitmentCodingTest;

  export const METADATA = {
    method: "PATCH",
    path: "/atsRecruitment/systemAdmin/codingTests",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/atsRecruitment/systemAdmin/codingTests";
  export const random = (): IPageIAtsRecruitmentCodingTest =>
    typia.random<IPageIAtsRecruitmentCodingTest>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information about a specific coding test assignment in ATS.
 *
 * Returns all details for a specific coding test record from
 * ats_recruitment_coding_tests, referenced by codingTestId. This includes
 * scheduling, delivery status, applicant and HR references, external provider
 * linkage, expiration dates, and all current state and tracking fields. Used by
 * HR and tech reviewers to monitor assignment progress and investigate
 * applicant issues.
 *
 * Authorization ensures HR can only see assignments for their postings, tech
 * reviewers see only their assignments, system admins have full access, and
 * applicants can view their own assignments. Sensitive provider integration
 * details may be masked except for system admins.
 *
 * Related operations include indexing (list view), and submission/feedback
 * tracking endpoints. Error handling surfaces not found, access violation, or
 * data corruption cases specifically.
 *
 * @param props.connection
 * @param props.codingTestId Unique identifier for the coding test assignment to
 *   be retrieved
 * @path /atsRecruitment/systemAdmin/codingTests/:codingTestId
 * @accessor api.functional.atsRecruitment.systemAdmin.codingTests.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier for the coding test assignment to be retrieved */
    codingTestId: string & tags.Format<"uuid">;
  };
  export type Response = IAtsRecruitmentCodingTest;

  export const METADATA = {
    method: "GET",
    path: "/atsRecruitment/systemAdmin/codingTests/:codingTestId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/atsRecruitment/systemAdmin/codingTests/${encodeURIComponent(props.codingTestId ?? "null")}`;
  export const random = (): IAtsRecruitmentCodingTest =>
    typia.random<IAtsRecruitmentCodingTest>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("codingTestId")(() => typia.assert(props.codingTestId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Updates an existing coding test assignment by codingTestId
 * (ats_recruitment_coding_tests table).
 *
 * This operation updates an existing coding test assignment in the ATS, as
 * referenced by its unique coding test ID. The update can include scheduling
 * changes (reschedule, change deadlines), provider metadata (such as updating
 * external provider IDs or URLs), or status updates if allowed. The operation
 * enforces access control (HR recruiter or system admin only), ensures audit
 * logging, and prevents modification for already closed or deleted test
 * records.
 *
 * If the coding test record does not exist, is no longer active, or is not in
 * an updatable state, an error will be returned. All relevant updates to audit
 * fields, scheduling, and referencing information are reflected. Business logic
 * may enforce that certain fields cannot be changed after delivery or after
 * submissions have started, as dictated by process policies.
 *
 * @param props.connection
 * @param props.codingTestId UUID of the coding test assignment to update.
 * @param props.body Fields to update for the coding test assignment, including
 *   schedule, provider info, and metadata.
 * @path /atsRecruitment/systemAdmin/codingTests/:codingTestId
 * @accessor api.functional.atsRecruitment.systemAdmin.codingTests.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /** UUID of the coding test assignment to update. */
    codingTestId: string & tags.Format<"uuid">;

    /**
     * Fields to update for the coding test assignment, including schedule,
     * provider info, and metadata.
     */
    body: IAtsRecruitmentCodingTest.IUpdate;
  };
  export type Body = IAtsRecruitmentCodingTest.IUpdate;
  export type Response = IAtsRecruitmentCodingTest;

  export const METADATA = {
    method: "PUT",
    path: "/atsRecruitment/systemAdmin/codingTests/:codingTestId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/atsRecruitment/systemAdmin/codingTests/${encodeURIComponent(props.codingTestId ?? "null")}`;
  export const random = (): IAtsRecruitmentCodingTest =>
    typia.random<IAtsRecruitmentCodingTest>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("codingTestId")(() => typia.assert(props.codingTestId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Soft deletes (marks as deleted) a coding test assignment by codingTestId
 * (ats_recruitment_coding_tests table).
 *
 * This operation soft deletes a coding test assignment identified by
 * codingTestId, by setting the deleted_at field to the current timestamp in the
 * ats_recruitment_coding_tests Prisma table. The operation is only available to
 * authorized HR recruiters or system administrators. When performed, it marks
 * the coding test as deleted but does not remove it from storage, ensuring that
 * records support audit/recovery/GDPR compliance.
 *
 * If the coding test is referenced by candidate submissions or is in a
 * non-deletable status (such as already closed or processed), the operation
 * will be rejected with an error. The operation ensures that no critical
 * in-progress results or downstream dependencies are orphaned by deletion.
 * Deletion attempts are logged for audit purposes, including timestamp and
 * actor.
 *
 * @param props.connection
 * @param props.codingTestId UUID of the coding test assignment to delete.
 * @path /atsRecruitment/systemAdmin/codingTests/:codingTestId
 * @accessor api.functional.atsRecruitment.systemAdmin.codingTests.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** UUID of the coding test assignment to delete. */
    codingTestId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/atsRecruitment/systemAdmin/codingTests/:codingTestId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/atsRecruitment/systemAdmin/codingTests/${encodeURIComponent(props.codingTestId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("codingTestId")(() => typia.assert(props.codingTestId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
