import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IEventRegistrationAdmin } from "../../../../structures/IEventRegistrationAdmin";

/**
 * Refresh admin JWT access token.
 *
 * Refresh JWT access tokens for authenticated admin users using valid refresh
 * tokens. Ensures secure session continuation. Endpoint accessible only to
 * already authenticated admins.
 *
 * @param props.connection
 * @param props.body Admin token refresh request containing valid refresh token
 * @setHeader token.access Authorization
 *
 * @path /auth/admin/refresh
 * @accessor api.functional.auth.admin.refresh.refreshAdminToken
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function refreshAdminToken(
  connection: IConnection,
  props: refreshAdminToken.Props,
): Promise<refreshAdminToken.Response> {
  const output: refreshAdminToken.Response =
    true === connection.simulate
      ? refreshAdminToken.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...refreshAdminToken.METADATA,
            path: refreshAdminToken.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace refreshAdminToken {
  export type Props = {
    /** Admin token refresh request containing valid refresh token */
    body: IEventRegistrationAdmin.IRefresh;
  };
  export type Body = IEventRegistrationAdmin.IRefresh;
  export type Response = IEventRegistrationAdmin.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/admin/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/admin/refresh";
  export const random = (): IEventRegistrationAdmin.IAuthorized =>
    typia.random<IEventRegistrationAdmin.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: refreshAdminToken.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: refreshAdminToken.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
