import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IRecipeSharingMealPlan } from "../../../../structures/IRecipeSharingMealPlan";
import { IRecipeSharingMealPlans } from "../../../../structures/IRecipeSharingMealPlans";
import { IPageIRecipeSharingMealPlans } from "../../../../structures/IPageIRecipeSharingMealPlans";
export * as entries from "./entries/index";

/**
 * Create a new meal plan for a user in the system. Requires providing the
 * owner's user ID, a unique meal plan name, and an optional description.
 *
 * Validations include ensuring the uniqueness of the meal plan name for the
 * given owner.
 *
 * Upon successful creation, the meal plan is recorded with timestamps for
 * auditing.
 *
 * Only regular and premium authenticated users authorized.
 *
 * Errors occur for duplicate meal plan names per user or invalid inputs.
 *
 * This operation supports user meal scheduling and planning functionality.
 *
 * @param props.connection
 * @param props.body Meal plan creation data including ownerUserId, name and
 *   optional description
 * @path /recipeSharing/regularUser/mealPlans
 * @accessor api.functional.recipeSharing.regularUser.mealPlans.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Meal plan creation data including ownerUserId, name and optional
     * description
     */
    body: IRecipeSharingMealPlan.ICreate;
  };
  export type Body = IRecipeSharingMealPlan.ICreate;
  export type Response = IRecipeSharingMealPlan;

  export const METADATA = {
    method: "POST",
    path: "/recipeSharing/regularUser/mealPlans",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/recipeSharing/regularUser/mealPlans";
  export const random = (): IRecipeSharingMealPlan =>
    typia.random<IRecipeSharingMealPlan>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * List user's meal plans with filtering and pagination.
 *
 * Search and retrieve a paginated list of meal plans for the authenticated
 * user. Supports filtering, sorting, and pagination via the request body.
 *
 * Meal plans associate recipes to calendar dates and meal slots and belong to a
 * specific user.
 *
 * The result returns meal plan summaries optimized for list views.
 *
 * Only meal plans owned by the requesting user are returned.
 *
 * Security measures ensure data privacy between users.
 *
 * Typical usage involves client-side page browsing and filtering.
 *
 * Errors return appropriate messages when filtering parameters are invalid.
 *
 * Response includes pagination metadata and the list of meal plans matching the
 * criteria.
 *
 * @param props.connection
 * @param props.body Search parameters and pagination options for meal plans
 * @path /recipeSharing/regularUser/mealPlans
 * @accessor api.functional.recipeSharing.regularUser.mealPlans.searchMealPlans
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function searchMealPlans(
  connection: IConnection,
  props: searchMealPlans.Props,
): Promise<searchMealPlans.Response> {
  return true === connection.simulate
    ? searchMealPlans.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...searchMealPlans.METADATA,
          path: searchMealPlans.path(),
          status: null,
        },
        props.body,
      );
}
export namespace searchMealPlans {
  export type Props = {
    /** Search parameters and pagination options for meal plans */
    body: IRecipeSharingMealPlans.IRequest;
  };
  export type Body = IRecipeSharingMealPlans.IRequest;
  export type Response = IPageIRecipeSharingMealPlans.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/recipeSharing/regularUser/mealPlans",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/recipeSharing/regularUser/mealPlans";
  export const random = (): IPageIRecipeSharingMealPlans.ISummary =>
    typia.random<IPageIRecipeSharingMealPlans.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: searchMealPlans.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: searchMealPlans.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve meal plan details by ID.
 *
 * Get detailed information of a specific meal plan identified by mealPlanId.
 *
 * This includes the meal plan metadata and its associated recipe entries
 * scheduling recipes to specific dates and meal slots.
 *
 * Access is restricted to the owner of the meal plan for privacy.
 *
 * Returns the meal plan with its recipes for client display and interaction.
 *
 * Errors occur if the meal plan does not exist or the user is unauthorized.
 *
 * This operation supports reading with full detail.
 *
 * @param props.connection
 * @param props.mealPlanId Unique identifier of the target meal plan
 * @path /recipeSharing/regularUser/mealPlans/:mealPlanId
 * @accessor api.functional.recipeSharing.regularUser.mealPlans.atMealPlan
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function atMealPlan(
  connection: IConnection,
  props: atMealPlan.Props,
): Promise<atMealPlan.Response> {
  return true === connection.simulate
    ? atMealPlan.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...atMealPlan.METADATA,
          path: atMealPlan.path(props),
          status: null,
        },
      );
}
export namespace atMealPlan {
  export type Props = {
    /** Unique identifier of the target meal plan */
    mealPlanId: string & tags.Format<"uuid">;
  };
  export type Response = IRecipeSharingMealPlans;

  export const METADATA = {
    method: "GET",
    path: "/recipeSharing/regularUser/mealPlans/:mealPlanId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/recipeSharing/regularUser/mealPlans/${encodeURIComponent(props.mealPlanId ?? "null")}`;
  export const random = (): IRecipeSharingMealPlans =>
    typia.random<IRecipeSharingMealPlans>();
  export const simulate = (
    connection: IConnection,
    props: atMealPlan.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: atMealPlan.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("mealPlanId")(() => typia.assert(props.mealPlanId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing meal plan by ID.
 *
 * Update the details of an existing meal plan such as name or description. The
 * mealPlanId path parameter specifies the target meal plan.
 *
 * Request body contains updated information, and only regular or premium users
 * owning the meal plan have authorization to update.
 *
 * The operation verifies the uniqueness of the name per owner and updates
 * timestamps.
 *
 * Error handling covers invalid mealPlanId, unauthorized access, or conflicting
 * meal plan names.
 *
 * Supports dynamic meal plan modification.
 *
 * @param props.connection
 * @param props.mealPlanId Unique identifier of the meal plan to update
 * @param props.body Updated meal plan data
 * @path /recipeSharing/regularUser/mealPlans/:mealPlanId
 * @accessor api.functional.recipeSharing.regularUser.mealPlans.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /** Unique identifier of the meal plan to update */
    mealPlanId: string & tags.Format<"uuid">;

    /** Updated meal plan data */
    body: IRecipeSharingMealPlan.IUpdate;
  };
  export type Body = IRecipeSharingMealPlan.IUpdate;
  export type Response = IRecipeSharingMealPlan;

  export const METADATA = {
    method: "PUT",
    path: "/recipeSharing/regularUser/mealPlans/:mealPlanId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/recipeSharing/regularUser/mealPlans/${encodeURIComponent(props.mealPlanId ?? "null")}`;
  export const random = (): IRecipeSharingMealPlan =>
    typia.random<IRecipeSharingMealPlan>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("mealPlanId")(() => typia.assert(props.mealPlanId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Delete an existing meal plan by ID.
 *
 * Permanently delete a meal plan by ID. The mealPlanId path parameter
 * identifies the meal plan to delete.
 *
 * This operation ensures only authorized regular and premium users can delete
 * their meal plans.
 *
 * Deleted records cannot be recovered.
 *
 * Errors return for invalid IDs or unauthorized access.
 *
 * Supports meal plan lifecycle management via removal.
 *
 * @param props.connection
 * @param props.mealPlanId Unique identifier of the meal plan to delete
 * @path /recipeSharing/regularUser/mealPlans/:mealPlanId
 * @accessor api.functional.recipeSharing.regularUser.mealPlans.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique identifier of the meal plan to delete */
    mealPlanId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/recipeSharing/regularUser/mealPlans/:mealPlanId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/recipeSharing/regularUser/mealPlans/${encodeURIComponent(props.mealPlanId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("mealPlanId")(() => typia.assert(props.mealPlanId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
