import { tags } from "typia";

/**
 * Meal plan entity representing user-defined schedules of recipes assigned to
 * dates and meal slots.
 *
 * This entity includes ownership, audit tracking with creation and update
 * timestamps, and supports soft deletion.
 *
 * Meal plans allow users to organize and automate meal selections, facilitating
 * personalized cooking and nutrition management.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IRecipeSharingMealPlan = {
  /** Primary Key. */
  id: string & tags.Format<"uuid">;

  /**
   * Owning user ID referencing recipe_sharing_regularusers.id or
   * recipe_sharing_premiumusers.id.
   */
  owner_user_id: string & tags.Format<"uuid">;

  /** Name of the meal plan for identification. */
  name: string;

  /** Optional description of the meal plan. */
  description?: string | null | undefined;

  /** Creation timestamp. */
  created_at: string & tags.Format<"date-time">;

  /** Last update timestamp. */
  updated_at: string & tags.Format<"date-time">;

  /** Soft delete timestamp; null if active. */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IRecipeSharingMealPlan {
  /** Request body schema for creating a new meal plan. */
  export type ICreate = {
    /** UUID of the user who will own the meal plan. */
    owner_user_id: string & tags.Format<"uuid">;

    /** Name of the new meal plan. */
    name: string;

    /** Optional description for the meal plan. */
    description?: string | null | undefined;
  };

  /**
   * Update data for modifying an existing meal plan.
   *
   * Allows changing the meal plan's display name and optional description.
   *
   * Does NOT permit updates to ownership or audit fields.
   */
  export type IUpdate = {
    /** Name of the meal plan for identification. */
    name: string;

    /** Optional description of the meal plan. */
    description?: string | null | undefined;
  };
}
