import { IPage } from "./IPage";
import { IChatAppAuthenticationSession } from "./IChatAppAuthenticationSession";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIChatAppAuthenticationSession = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: IChatAppAuthenticationSession[];
};
