import { tags } from "typia";

import { IAuthorizationToken } from "./IAuthorizationToken";

/**
 * Nurse core profile, credential, and account metadata as stored in the
 * healthcare platform. Fields precisely match the healthcare_platform_nurses
 * schema/table and are used for authentication, display, scheduling, audit, and
 * compliance. Personal health and employment-related data are excluded from
 * this type; use for admins, HR, clinical apps, or audits only.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IHealthcarePlatformNurse = {
  /**
   * Unique identifier for the nurse. Universally unique identifier (UUID).
   * Set by the system on creation. Used for PK in database and for RBAC,
   * audit, and lookup.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Business email for login and notifications, must be globally unique and
   * use a business domain (not public email like @gmail.com). Used for
   * authentication and contact.
   */
  email: string & tags.Format<"email">;

  /**
   * Full legal name of the nurse as used for licensure, documentation, and
   * identity. Must match credentials. Used for display and legal compliance.
   */
  full_name: string;

  /**
   * State-issued nurse license/certification number, unique for each nurse in
   * compliance/audit workflows. Required for employment, credential check,
   * and regulatory compliance.
   */
  license_number: string;

  /**
   * Primary specialty of nursing practice (optional), e.g., ICU, Med/Surg,
   * Pediatrics. Used for search, scheduling, and workforce management.
   */
  specialty?: string | undefined;

  /**
   * Business/organization or personal phone for shift, security, and platform
   * notifications. Optional.
   */
  phone?: string | undefined;

  /**
   * Timestamp (ISO 8601) when nurse account was created. Set by the platform
   * system for audit/compliance.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp (ISO 8601) of last update to this nurse record. Used for change
   * tracking and audit.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft deletion/archival tracking, records when the nurse was
   * deactivated/logically deleted (ISO date-time), or null if still active.
   * This field is used for audit/compliance; when set, the nurse is logically
   * deleted but still present in the system until regulatory retention
   * requirements are met.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IHealthcarePlatformNurse {
  /**
   * Request body for nurse registration (join) API. Used for onboarding a new
   * nurse with all required profile and credential information. All fields
   * map to columns in the healthcare_platform_nurses table.
   */
  export type IJoin = {
    /**
     * Email address for login and notifications. Must be unique to this
     * nurse within the system. Only business emails allowed; personal email
     * domains (e.g., gmail, yahoo) are not valid for clinical staff
     * accounts. Used for notifications, password resets, and system
     * identification.
     */
    email: string & tags.Format<"email">;

    /**
     * Full legal name of the nurse. Used for credentialing, patient-facing
     * display, and audit. Should match state license records. Cannot be
     * omitted for staff accounts.
     */
    full_name: string;

    /**
     * State-issued license or certification number. Must be unique to each
     * nurse. Required for credentialing/audit. Used for regulatory and
     * compliance workflows.
     */
    license_number: string;

    /**
     * Primary clinical area of nursing for the nurse (optional, e.g., ICU,
     * Med/Surg). This field is used for clinical assignment and role
     * mapping. May be null if the nurse is not assigned a specialty.
     */
    specialty?: string | null | undefined;

    /**
     * Work or personal phone number for shift notifications, security
     * alerts, or urgent communications. This field is optional and may be
     * null if no contact number is available.
     */
    phone?: string | null | undefined;

    /**
     * Credential for authentication. Must be provided if using local
     * authentication (password login); required complexity enforced by
     * policy. Not returned in any response. Never stored as plain text.
     */
    password?: string | undefined;
  };

  /**
   * Response body for authorized nurse session. Contains all non-sensitive
   * user and credential identifiers for the nurse, excluding any password
   * hashes or secrets. Provides JWT session tokens for authentication.
   */
  export type IAuthorized = {
    /**
     * Unique identifier for the nurse user (UUID). Used to reference the
     * account throughout the platform.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Nurse's business email address. Used for login, notifications, and
     * account recovery.
     */
    email: string & tags.Format<"email">;

    /**
     * The full legal name of the nurse. Used for credentials, display, and
     * compliance.
     */
    full_name: string;

    /**
     * Nurse's state-issued license or certification number. Uniquely
     * identifies clinical staff and is required for audit/compliance.
     */
    license_number: string;

    /**
     * The primary clinical area of nursing for the nurse (optional). May be
     * null if unspecified.
     */
    specialty?: string | null | undefined;

    /**
     * Contact phone for notifications and shift/security alerts. May be
     * null if not provided.
     */
    phone?: string | null | undefined;

    /** Timestamp when the nurse account was created (ISO 8601, UTC). */
    created_at: string & tags.Format<"date-time">;

    /** Timestamp when nurse account was last updated (ISO 8601, UTC). */
    updated_at: string & tags.Format<"date-time">;

    /**
     * Soft deletion/archival tracking, records when the nurse was
     * deactivated/logically deleted (ISO date-time), or null if still
     * active. This field is used for audit/compliance; when set, the nurse
     * is logically deleted but still present in the system until regulatory
     * retention requirements are met.
     */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** JWT token information for authentication */
    token: IAuthorizationToken;
  };

  /**
   * Request body for nurse login/authentication API. Used to start a new
   * authenticated session for a nurse account.
   */
  export type ILogin = {
    /**
     * Nurse's email address for login (business email only). Must match an
     * active account.
     */
    email: string & tags.Format<"email">;

    /**
     * Login credential. Not returned in any response, must match nurse's
     * authentication record.
     */
    password: string;
  };

  /**
   * Request body for refreshing nurse authentication tokens. Supplies the
   * refresh_token that must be validated for the nurse's active session.
   */
  export type IRefresh = {
    /**
     * Refresh token string issued previously at login or join. Used to
     * renew JWT authentication session for the nurse.
     */
    refresh_token: string;
  };

  /**
   * Advanced search/filter parameters for nurse list endpoints. Used in PATCH
   * and similar query API methods. Supports pagination and sorting via parent
   * IPage schema.
   */
  export type IRequest = {
    /** Partial/full name search filter for nurses. */
    full_name?: string | undefined;

    /**
     * Filter for nurse email address (case-insensitive partial match
     * supported).
     */
    email?: string | undefined;

    /** Search by nurse license number. */
    license_number?: string | undefined;

    /** Search by nurse specialty. */
    specialty?: string | undefined;

    /** Filter by nurse account, employment or credentialing status. */
    status?: string | undefined;
  };

  /**
   * Payload for creating a nurse account (on registration/join). Only
   * required user identity and credential fields are accepted. No ID,
   * timestamps, or managed audit fields.
   */
  export type ICreate = {
    /**
     * Business email for login and notifications, must be globally unique.
     * Used for authentication and contact.
     */
    email: string & tags.Format<"email">;

    /**
     * Full legal name of the nurse as used for licensure, documentation,
     * and identity.
     */
    full_name: string;

    /**
     * State-issued nurse license/certification number, unique for each
     * nurse in compliance/audit workflows.
     */
    license_number: string;

    /**
     * Primary clinical specialty area (optional) (e.g., ICU, Pediatrics,
     * etc).
     */
    specialty?: string | null | undefined;

    /** Business phone or personal number for shift notifications and alerts. */
    phone?: string | null | undefined;
  };

  /**
   * Payload for partial update of an existing nurse profile. All fields
   * optional. Only non-managed fields may be updated.
   */
  export type IUpdate = {
    /**
     * Business email for notifications and login (must remain unique if
     * changed).
     */
    email?: (string & tags.Format<"email">) | undefined;

    /** Legal name (for updates due to marriage or legal adjustment). */
    full_name?: string | undefined;

    /**
     * State-issued nurse credential/licensure number (may change if
     * re-licensed).
     */
    license_number?: string | undefined;

    /** Primary specialty updated (optional). */
    specialty?: string | null | undefined;

    /** Updated business or personal phone for notifications. */
    phone?: string | null | undefined;
  };

  /**
   * Summary DTO for nurse entity for list and pagination results. Includes
   * only identification and distinguishing fields. Does not contain phone or
   * audit/mgmt fields.
   */
  export type ISummary = {
    /** Unique identifier for the nurse record/account (uuid). */
    id: string & tags.Format<"uuid">;

    /** Legal full name of the nurse (for display and search). */
    full_name: string;

    /** Primary (business) email for identity and contact. */
    email: string & tags.Format<"email">;

    /** State-issued nurse credential number for compliance and staff audits. */
    license_number: string;

    /** Primary specialty (optional, for search/display). */
    specialty?: string | null | undefined;
  };
}
