import { tags } from "typia";

import { IHealthcarePlatformCalendarSetting } from "./IHealthcarePlatformCalendarSetting";

/**
 * Array/list of calendar/locale/region settings available in the platform. Used
 * for UI population, localization logic, and regional configuration. Each
 * object in the array defines a distinct context or policy for an organization
 * or department.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IHealthcarePlatformCalendarSettings =
  IHealthcarePlatformCalendarSetting[];
export namespace IHealthcarePlatformCalendarSettings {
  /**
   * Input DTO for updating an existing calendar/locale/regional settings
   * entity. All fields are optional, only provided values are updated.
   */
  export type IUpdate = {
    /** Updated organization context for this setting (nullable for global) */
    healthcare_platform_organization_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Updated department context, nullable for org/global scope */
    healthcare_platform_department_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Updated language code for this context */
    language?: string | undefined;

    /** Updated timezone string in IANA format */
    timezone?: string | undefined;

    /** Updated date display format */
    date_format?: string | undefined;

    /** Updated time display format */
    time_format?: string | undefined;

    /** Updated number formatting convention. */
    number_format?: string | undefined;
  };
}
