import { tags } from "typia";

/**
 * Billing payment plan entity as stored in
 * healthcare_platform_billing_payment_plans. Describes payment arrangements for
 * invoices: type, terms, status, start/end, audit timestamps, and soft-deletion
 * marker.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IHealthcarePlatformBillingPaymentPlan = {
  /** Primary key for payment plan. */
  id: string;

  /** Invoice for which this plan exists. */
  invoice_id: string;

  /**
   * Installment/payment plan type (e.g., self-pay, insurance, payment
   * deferral, promissory).
   */
  plan_type: string;

  /** Description of payment terms. */
  terms_description: string;

  /**
   * Status of payment plan (e.g., active, completed, defaulted, cancelled,
   * expired).
   */
  status: string;

  /** Total amount to be paid under this plan. */
  total_amount: number;

  /** Scheduled start date (ISO 8601) */
  start_date: string;

  /** Plan end date (ISO 8601) or null if still pending. */
  end_date?: string | null | undefined;

  /** Record creation timestamp (ISO 8601 date-time) */
  created_at: string;

  /** Record last update timestamp (ISO 8601 date-time) */
  updated_at: string;

  /** Soft-delete timestamp. Null if active. */
  deleted_at?: string | null | undefined;
};
export namespace IHealthcarePlatformBillingPaymentPlan {
  /**
   * Request body type for searching/filtering payment plans in
   * healthcare_platform_billing_payment_plans. All fields optional. Used for
   * paginated search.
   */
  export type IRequest = {
    /** Invoice for which the payment plan is or will be created. */
    invoice_id?: string | undefined;

    /** Installment/payment plan type (e.g., self-pay, insurance, deferral). */
    plan_type?: string | undefined;

    /**
     * Current status of payment plan (e.g., active, completed, defaulted,
     * expired, cancelled).
     */
    status?: string | undefined;

    /** ISO 8601 date string for scheduled/actual payment plan start. */
    start_date?: string | undefined;

    /** ISO 8601 date string for payment plan end. */
    end_date?: string | undefined;

    /** Minimum total amount value for filtering, inclusive. */
    total_amount_min?: number | undefined;

    /** Maximum total amount value for filtering, inclusive. */
    total_amount_max?: number | undefined;

    /** Page number for pagination (starts at 1). */
    page?: number | undefined;

    /** Number of records per page. */
    limit?: number | undefined;

    /** Field name to sort results by. */
    sort?: string | undefined;

    /** Sort direction for the given field. */
    order?: "asc" | "desc" | undefined;
  };

  /**
   * Request body for creating a new billing payment plan in
   * healthcare_platform_billing_payment_plans. References invoice_id and
   * defines business terms for the schedule.
   */
  export type ICreate = {
    /** Invoice UUID for which plan is established. */
    invoice_id: string;

    /**
     * Installment or payment plan type (e.g., self-pay, insurance,
     * promissory).
     */
    plan_type: string;

    /**
     * Human-readable description of payment terms (e.g., amount per period,
     * number of installments).
     */
    terms_description: string;

    /** Status of payment plan (active, completed, defaulted, expired, etc.). */
    status: string;

    /** Total amount to be paid as per the payment plan. */
    total_amount: number;

    /** Plan start date (ISO 8601 date string) */
    start_date: string;

    /**
     * Planned or actual payment plan end date (ISO 8601 date string or null
     * for open-ended).
     */
    end_date?: string | null | undefined;
  };

  /**
   * Update DTO payload for billing payment plans, supporting revision of
   * type, description, status, amount, and payment window as used by billing
   * finance staff. All properties are optional, and only supplied fields are
   * updated. Dates use ISO 8601 string format.
   */
  export type IUpdate = {
    /**
     * Payment plan type. Examples: 'self-pay', 'insurance', 'deferred',
     * 'promissory'.
     */
    plan_type?: string | undefined;

    /**
     * Human-readable description of payment plan terms, such as payment
     * amount/frequency, comment, etc.
     */
    terms_description?: string | undefined;

    /**
     * Plan status. Examples: 'active', 'completed', 'defaulted',
     * 'cancelled', 'expired'.
     */
    status?: string | undefined;

    /**
     * Total amount for the payment plan in major currency units (e.g.,
     * 123.45 for $123.45).
     */
    total_amount?: number | undefined;

    /** ISO 8601 datetime when the plan begins. */
    start_date?: (string & tags.Format<"date-time">) | undefined;

    /** ISO 8601 datetime for planned or actual plan completion/end. */
    end_date?: (string & tags.Format<"date-time">) | undefined;
  };

  /**
   * Summary view for paginated billing payment plan lists—fewer fields,
   * suitable for IPage responses. Includes plan key, plan_type, status, total
   * amount, start/end, primary status, and audit dates.
   */
  export type ISummary = {
    /** UUID of the payment plan (primary key). */
    id: string & tags.Format<"uuid">;

    /** UUID of the parent billing invoice. */
    invoice_id: string & tags.Format<"uuid">;

    /**
     * Installment/payment plan type (e.g., self-pay, insurance, payment
     * deferral, promissory).
     */
    plan_type: string;

    /** Status of payment plan (enum). */
    status: "active" | "completed" | "defaulted" | "cancelled" | "expired";

    /** Total amount to be paid under this plan. */
    total_amount: number;

    /** Plan start date (ISO 8601). */
    start_date: string & tags.Format<"date-time">;

    /** End date if known (ISO 8601 or null). */
    end_date?: (string & tags.Format<"date-time">) | null | undefined;

    /** Created timestamp. */
    created_at: string & tags.Format<"date-time">;

    /** Last update timestamp. */
    updated_at?: (string & tags.Format<"date-time">) | undefined;
  };
}
