import { tags } from "typia";

/**
 * Reviews and decisions made by moderators regarding flagged or reported
 * content. Includes reference to the moderator, related flag or report,
 * decision details, and audit timestamps. Facilitates moderation workflow
 * tracking and accountability.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityAiModeratorReviews = {
  /** Primary Key. */
  id: string & tags.Format<"uuid">;

  /** Moderator performing the review. {@link community_ai_moderators.id} */
  community_ai_moderator_id: string & tags.Format<"uuid">;

  /**
   * Referenced content flag under review.
   * {@link community_ai_content_flags.id}
   */
  community_ai_content_flag_id?:
    | (string & tags.Format<"uuid">)
    | null
    | undefined;

  /** Referenced user report under review. {@link community_ai_user_reports.id} */
  community_ai_user_report_id?:
    | (string & tags.Format<"uuid">)
    | null
    | undefined;

  /** Decision outcome such as 'approved', 'rejected', or 'needs more info'. */
  decision: string;

  /** Additional comments or reasons by the moderator. */
  comments?: string | null | undefined;

  /** Timestamp when the review was created. */
  created_at: string & tags.Format<"date-time">;

  /** Timestamp when the review was last updated. */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Nullable soft delete timestamp to mark if the review is deleted and
   * hidden.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ICommunityAiModeratorReviews {
  /**
   * Payload to create a new moderator review associated with content flags or
   * user reports.
   */
  export type ICreate = {
    /** Moderator performing the review */
    community_ai_moderator_id: string & tags.Format<"uuid">;

    /** Referenced content flag under review */
    community_ai_content_flag_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Referenced user report under review */
    community_ai_user_report_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /** Decision outcome such as 'approved', 'rejected', or 'needs more info' */
    decision: string;

    /** Additional comments or reasons by the moderator */
    comments?: string | null | undefined;
  };

  /** Update input for moderator review, allowing partial modifications. */
  export type IUpdate = {
    /** Moderator performing the review. {@link community_ai_moderators.id} */
    community_ai_moderator_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Referenced content flag under review.
     * {@link community_ai_content_flags.id}
     */
    community_ai_content_flag_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /**
     * Referenced user report under review.
     * {@link community_ai_user_reports.id}
     */
    community_ai_user_report_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /**
     * Decision outcome such as 'approved', 'rejected', or 'needs more
     * info'.
     */
    decision?: string | undefined;

    /** Additional comments or reasons by the moderator. */
    comments?: string | null | undefined;

    /** Timestamp when the review was created. */
    created_at?: (string & tags.Format<"date-time">) | undefined;

    /** Timestamp when the review was last updated. */
    updated_at?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Nullable soft delete timestamp to mark if the review is deleted and
     * hidden.
     */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };

  /**
   * Summary view of moderator reviews.
   *
   * Captures key decision information and creation timestamp, referencing the
   * community_ai_moderator_reviews table.
   *
   * Suitable for moderation list displays or audit summarization.
   */
  export type ISummary = {
    /** Unique identifier of the moderator review */
    id: string & tags.Format<"uuid">;

    /**
     * Decision outcome such as 'approved', 'rejected', or 'needs more
     * info'.
     */
    decision: string;

    /** Timestamp when the review was created. */
    created_at: string & tags.Format<"date-time">;
  };
}
