import { tags } from "typia";

/**
 * Community AI audit log record representing edit histories for posts and
 * comments. This entity captures who edited the content, what was edited,
 * previous and new content, and timestamps for audit purposes.
 *
 * All fields adhere strictly to the Prisma schema definition with accurate
 * format annotations to ensure data integrity and conformance with expected
 * UUID and date-time formats.
 *
 * This type is key for auditing content modifications and supporting content
 * traceability and compliance requirements.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityAiAuditEditHistory = {
  /**
   * Unique identifier of the audit log entry.
   *
   * @example
   *   9e8c7f4a-2bcd-4a01-b629-0b27a9177193
   */
  id: string & tags.Format<"uuid">;

  /**
   * Identifier of the member who performed the edit.
   *
   * @example
   *   65f3b3f4-0d1b-48fa-a2e7-332b0ca682d6
   */
  edited_by_member_id: string & tags.Format<"uuid">;

  /**
   * Identifier of the post that was edited, if applicable.
   *
   * @example
   *   25cd6870-d772-429d-8b53-f37f8d0e4ae8
   *
   * @nullable
   */
  post_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Identifier of the comment that was edited, if applicable.
   *
   * @example
   *   739e2c7c-2310-4b11-88c8-2157a8e334ec
   *
   * @nullable
   */
  comment_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Type of edit performed (e.g., "content_update", "title_change").
   *
   * @example
   *   content_update;
   */
  edit_type: string;

  /**
   * Content before the edit.
   *
   * @nullable
   */
  before_edit?: string | null | undefined;

  /**
   * Content after the edit.
   *
   * @nullable
   */
  after_edit?: string | null | undefined;

  /**
   * When the edit was recorded.
   *
   * @example
   *   2025-09-15T00:00:00.000Z
   */
  created_at: string & tags.Format<"date-time">;
};
export namespace ICommunityAiAuditEditHistory {
  /**
   * Request type for searching and paginating Community AI Edit Histories.
   *
   * This interface supports filtering, sorting, and pagination parameters to
   * query edit history logs efficiently.
   */
  export type IRequest = {
    /**
     * Page number to retrieve.
     *
     * Number must be an unsigned 32-bit integer.
     *
     * @example
     *   1;
     *
     * @default 1
     */
    page?: (number & tags.Type<"int32">) | null | undefined;

    /**
     * Number of items per page.
     *
     * Number must be an unsigned 32-bit integer.
     *
     * @example
     *   20;
     *
     * @default 20
     */
    limit?: (number & tags.Type<"int32">) | null | undefined;

    /**
     * Filter by member ID who edited.
     *
     * Member who performed the edit, UUID format.
     *
     * @nullable
     */
    edited_by_member_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by post ID.
     *
     * Post that was edited, UUID format, nullable.
     *
     * @nullable
     */
    post_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by comment ID.
     *
     * Comment that was edited, UUID format, nullable.
     *
     * @nullable
     */
    comment_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by edit type.
     *
     * Type string to filter edits by type.
     *
     * @nullable
     */
    edit_type?: string | null | undefined;

    /**
     * Filter for edits recorded after this date.
     *
     * ISO 8601 date-time string, nullable.
     *
     * @nullable
     */
    created_after?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Filter for edits recorded before this date.
     *
     * ISO 8601 date-time string, nullable.
     *
     * @nullable
     */
    created_before?: (string & tags.Format<"date-time">) | null | undefined;

    /** Description of the request for search and pagination parameters. */
    description?: string | undefined;
  };

  /** Create new Community AI edit history record */
  export type ICreate = {
    /**
     * Identifier of the member who performed the edit.
     *
     * @example
     *   65f3b3f4-0d1b-48fa-a2e7-332b0ca682d6
     */
    edited_by_member_id: string & tags.Format<"uuid">;

    /**
     * Identifier of the post that was edited, if applicable.
     *
     * @example
     *   25cd6870-d772-429d-8b53-f37f8d0e4ae8
     *
     * @nullable
     */
    post_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Identifier of the comment that was edited, if applicable.
     *
     * @example
     *   739e2c7c-2310-4b11-88c8-2157a8e334ec
     *
     * @nullable
     */
    comment_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Type of edit performed (e.g., "content_update", "title_change").
     *
     * @example
     *   content_update;
     */
    edit_type: string;

    /**
     * Content before the edit.
     *
     * @nullable
     */
    before_edit?: string | null | undefined;

    /**
     * Content after the edit.
     *
     * @nullable
     */
    after_edit?: string | null | undefined;
  };

  /** Update properties of Community AI edit history record */
  export type IUpdate = {
    /**
     * Identifier of the member who performed the edit.
     *
     * @example
     *   65f3b3f4-0d1b-48fa-a2e7-332b0ca682d6
     *
     * @nullable
     */
    edited_by_member_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Identifier of the post that was edited, if applicable.
     *
     * @example
     *   25cd6870-d772-429d-8b53-f37f8d0e4ae8
     *
     * @nullable
     */
    post_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Identifier of the comment that was edited, if applicable.
     *
     * @example
     *   739e2c7c-2310-4b11-88c8-2157a8e334ec
     *
     * @nullable
     */
    comment_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Type of edit performed (e.g., "content_update", "title_change").
     *
     * @nullable
     */
    edit_type?: string | null | undefined;

    /**
     * Content before the edit.
     *
     * @nullable
     */
    before_edit?: string | null | undefined;

    /**
     * Content after the edit.
     *
     * @nullable
     */
    after_edit?: string | null | undefined;
  };
}
