import { tags } from "typia";

/**
 * Stores authentication sessions for community AI members, including session
 * tokens, expiration info, IP address, and user agent data. This model
 * facilitates session lifecycle management, revocation, and auditing.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityAiUserSession = {
  /** Primary Key. */
  id: string & tags.Format<"uuid">;

  /** Associated community AI member's id. */
  community_ai_member_id: string & tags.Format<"uuid">;

  /** Unique token used for session authentication. */
  session_token: string;

  /** Timestamp when the session expires. */
  expires_at: string & tags.Format<"date-time">;

  /** Optional token used to refresh the session. */
  refresh_token?: string | null | undefined;

  /** Expiration timestamp for the refresh token. */
  refresh_token_expires_at?:
    | (string & tags.Format<"date-time">)
    | null
    | undefined;

  /** IP address from which the session was initiated. */
  ip_address?: string | null | undefined;

  /** User agent string of the client device. */
  user_agent?: string | null | undefined;

  /** Timestamp of session creation. */
  created_at: string & tags.Format<"date-time">;

  /** Timestamp of last update to the session record. */
  updated_at: string & tags.Format<"date-time">;

  /** Timestamp when the session was soft deleted or invalidated. */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ICommunityAiUserSession {
  /**
   * Stores authentication sessions for community AI members, including
   * session tokens, expiration info, IP address, and user agent data. This
   * model facilitates session lifecycle management, revocation, and
   * auditing.
   */
  export type ICreate = {
    /** Associated community AI member's id. */
    community_ai_member_id: string & tags.Format<"uuid">;

    /** Unique token used for session authentication. */
    session_token: string;

    /** Timestamp when the session expires. */
    expires_at: string & tags.Format<"date-time">;

    /** Optional token used to refresh the session. */
    refresh_token?: string | null | undefined;

    /** Expiration timestamp for the refresh token. */
    refresh_token_expires_at?:
      | (string & tags.Format<"date-time">)
      | null
      | undefined;

    /** IP address from which the session was initiated. */
    ip_address?: string | null | undefined;

    /** User agent string of the client device. */
    user_agent?: string | null | undefined;
  };

  /**
   * Stores authentication sessions for community AI members, including
   * session tokens, expiration info, IP address, and user agent data. This
   * model facilitates session lifecycle management, revocation, and
   * auditing.
   */
  export type IUpdate = {
    /** Associated community AI member's id. */
    community_ai_member_id?: (string & tags.Format<"uuid">) | undefined;

    /** Unique token used for session authentication. */
    session_token?: string | undefined;

    /** Timestamp when the session expires. */
    expires_at?: (string & tags.Format<"date-time">) | undefined;

    /** Optional token used to refresh the session. */
    refresh_token?: string | null | undefined;

    /** Expiration timestamp for the refresh token. */
    refresh_token_expires_at?:
      | (string & tags.Format<"date-time">)
      | null
      | undefined;

    /** IP address from which the session was initiated. */
    ip_address?: string | null | undefined;

    /** User agent string of the client device. */
    user_agent?: string | null | undefined;

    /** Timestamp when the session was soft deleted or invalidated. */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };
}
