import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ITelegramFileDownloaderEndUser } from "../../../../../structures/ITelegramFileDownloaderEndUser";

/**
 * Reset password for endUser account securely.
 *
 * Password reset operation for end users to securely change their password
 * after verification. Relies on telegram_file_downloader_endusers password_hash
 * field for updating credentials. Supports member-kind users in maintaining
 * account security via password recovery.
 *
 * @param props.connection
 * @param props.body Request body for password reset operation for endUser
 * @path /auth/endUser/password/reset
 * @accessor api.functional.auth.endUser.password.reset.resetPassword
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function resetPassword(
  connection: IConnection,
  props: resetPassword.Props,
): Promise<resetPassword.Response> {
  return true === connection.simulate
    ? resetPassword.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...resetPassword.METADATA,
          path: resetPassword.path(),
          status: null,
        },
        props.body,
      );
}
export namespace resetPassword {
  export type Props = {
    /** Request body for password reset operation for endUser */
    body: ITelegramFileDownloaderEndUser.IResetPassword;
  };
  export type Body = ITelegramFileDownloaderEndUser.IResetPassword;
  export type Response = ITelegramFileDownloaderEndUser.IResetPasswordResponse;

  export const METADATA = {
    method: "POST",
    path: "/auth/endUser/password/reset",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/endUser/password/reset";
  export const random =
    (): ITelegramFileDownloaderEndUser.IResetPasswordResponse =>
      typia.random<ITelegramFileDownloaderEndUser.IResetPasswordResponse>();
  export const simulate = (
    connection: IConnection,
    props: resetPassword.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: resetPassword.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
