import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";
import { postenterpriseLmsExternalLearnerDirectMessages } from "../../../../providers/postenterpriseLmsExternalLearnerDirectMessages";
import { ExternallearnerAuth } from "../../../../decorators/ExternallearnerAuth";
import { ExternallearnerPayload } from "../../../../decorators/payload/ExternallearnerPayload";
import { patchenterpriseLmsExternalLearnerDirectMessages } from "../../../../providers/patchenterpriseLmsExternalLearnerDirectMessages";
import { getenterpriseLmsExternalLearnerDirectMessagesDirectMessageId } from "../../../../providers/getenterpriseLmsExternalLearnerDirectMessagesDirectMessageId";

import { IEnterpriseLmsDirectMessage } from "../../../../api/structures/IEnterpriseLmsDirectMessage";
import { IPageIEnterpriseLmsDirectMessage } from "../../../../api/structures/IPageIEnterpriseLmsDirectMessage";

@Controller("/enterpriseLms/externalLearner/directMessages")
export class EnterpriselmsExternallearnerDirectmessagesController {
  /**
   * Create and send a new direct message between users.
   *
   * Send a new private direct message within the enterprise LMS platform. The
   * message is stored in the enterprise_lms_direct_messages table with sender
   * and recipient user identifiers, message content, and sent timestamp.
   *
   * The sender and recipient must be valid users with appropriate permissions.
   * The message content should comply with content guidelines.
   *
   * Upon successful creation, the newly saved direct message is returned.
   *
   * Only authenticated users can send direct messages.
   *
   * This operation supports user communication and collaboration.
   *
   * @param connection
   * @param body Direct message creation payload including sender, recipient,
   *   and message content
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @ExternallearnerAuth()
    externalLearner: ExternallearnerPayload,
    @TypedBody()
    body: IEnterpriseLmsDirectMessage.ICreate,
  ): Promise<IEnterpriseLmsDirectMessage> {
    try {
      return await postenterpriseLmsExternalLearnerDirectMessages({
        externalLearner,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Search and retrieve a list of direct messages with filters and pagination.
   *
   * Retrieve a filtered and paginated list of direct messages exchanged between
   * users in the enterprise LMS platform. This operation accepts various search
   * parameters such as sender ID, recipient ID, date range, and message content
   * keywords to facilitate detailed querying.
   *
   * Direct messages represent private communications stored in the
   * enterprise_lms_direct_messages table. The system applies tenant isolation
   * and access control to ensure message confidentiality.
   *
   * The filtered data is returned with pagination to support efficient client
   * rendering. This is a read-only, user-level operation accessible to
   * authenticated users.
   *
   * @param connection
   * @param body Search parameters and pagination settings for direct messages
   *   filtering
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @ExternallearnerAuth()
    externalLearner: ExternallearnerPayload,
    @TypedBody()
    body: IEnterpriseLmsDirectMessage.IRequest,
  ): Promise<IPageIEnterpriseLmsDirectMessage.ISummary> {
    try {
      return await patchenterpriseLmsExternalLearnerDirectMessages({
        externalLearner,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve details of a specific direct message.
   *
   * Retrieve detailed information of a single direct message identified by
   * directMessageId. The direct message includes sender, recipient, message
   * content, sent/read timestamps, and metadata.
   *
   * This data is tenant-isolated and access-controlled according to user
   * permissions.
   *
   * Providing a valid UUID parameter for directMessageId is required.
   *
   * Only authorized authenticated users can perform this operation.
   *
   * This operation supports use cases such as message viewing and auditing.
   *
   * @param connection
   * @param directMessageId Unique identifier of the direct message to retrieve
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":directMessageId")
  public async at(
    @ExternallearnerAuth()
    externalLearner: ExternallearnerPayload,
    @TypedParam("directMessageId")
    directMessageId: string & tags.Format<"uuid">,
  ): Promise<IEnterpriseLmsDirectMessage> {
    try {
      return await getenterpriseLmsExternalLearnerDirectMessagesDirectMessageId(
        {
          externalLearner,
          directMessageId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
