import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

/**
 * Delete a content localization for a given content.
 *
 * Delete a specific content localization associated with a particular content.
 * This operation permanently removes the localization entry from the system.
 *
 * Security: Only authorized users with appropriate permissions to manage
 * content localizations can perform this operation.
 *
 * Relationships: The content localization belongs to a content item identified
 * by contentId. The content in turn is tenant isolated to ensure
 * multi-organizational data security.
 *
 * Validation: Path parameters contentId and id must be valid UUIDs representing
 * existing records.
 *
 * Behavior: This operation performs a hard delete, removing the localization
 * record completely and irreversibly.
 *
 * Related APIs: List all localizations for a content, Add a new localization,
 * Update an existing localization.
 *
 * Errors: Returns 404 if content or localization does not exist, 403 for
 * unauthorized users.
 *
 * @param props.connection
 * @param props.contentId Unique identifier of the content
 * @param props.id Unique identifier of the content localization
 * @path /enterpriseLms/organizationAdmin/contents/:contentId/contentLocalizations/:id
 * @accessor api.functional.enterpriseLms.organizationAdmin.contents.contentLocalizations.eraseContentLocalization
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function eraseContentLocalization(
  connection: IConnection,
  props: eraseContentLocalization.Props,
): Promise<void> {
  return true === connection.simulate
    ? eraseContentLocalization.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseContentLocalization.METADATA,
          path: eraseContentLocalization.path(props),
          status: null,
        },
      );
}
export namespace eraseContentLocalization {
  export type Props = {
    /** Unique identifier of the content */
    contentId: string & tags.Format<"uuid">;

    /** Unique identifier of the content localization */
    id: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/enterpriseLms/organizationAdmin/contents/:contentId/contentLocalizations/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/enterpriseLms/organizationAdmin/contents/${encodeURIComponent(props.contentId ?? "null")}/contentLocalizations/${encodeURIComponent(props.id ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: eraseContentLocalization.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseContentLocalization.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("contentId")(() => typia.assert(props.contentId));
      assert.param("id")(() => typia.assert(props.id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
