import { Module } from "@nestjs/common";

import { AuthSystemadminController } from "./controllers/auth/systemAdmin/AuthSystemadminController";
import { AuthOrganizationadminController } from "./controllers/auth/organizationAdmin/AuthOrganizationadminController";
import { AuthDepartmentmanagerController } from "./controllers/auth/departmentManager/AuthDepartmentmanagerController";
import { AuthContentcreatorinstructorController } from "./controllers/auth/contentCreatorInstructor/AuthContentcreatorinstructorController";
import { AuthCorporatelearnerController } from "./controllers/auth/corporateLearner/AuthCorporatelearnerController";
import { AuthExternallearnerJoinController } from "./controllers/auth/externalLearner/join/AuthExternallearnerJoinController";
import { AuthExternallearnerRefreshController } from "./controllers/auth/externalLearner/refresh/AuthExternallearnerRefreshController";
import { AuthGuestController } from "./controllers/auth/guest/AuthGuestController";
import { EnterpriselmsSystemadminTenantsController } from "./controllers/enterpriseLms/systemAdmin/tenants/EnterpriselmsSystemadminTenantsController";
import { EnterpriselmsOrganizationadminTenantsTenantsettingsController } from "./controllers/enterpriseLms/organizationAdmin/tenants/tenantSettings/EnterpriselmsOrganizationadminTenantsTenantsettingsController";
import { EnterpriselmsSystemadminTenantsTenantsettingsController } from "./controllers/enterpriseLms/systemAdmin/tenants/tenantSettings/EnterpriselmsSystemadminTenantsTenantsettingsController";
import { EnterpriselmsSystemadminSystemconfigurationsController } from "./controllers/enterpriseLms/systemAdmin/systemConfigurations/EnterpriselmsSystemadminSystemconfigurationsController";
import { EnterpriselmsSystemadminAuditlogsController } from "./controllers/enterpriseLms/systemAdmin/auditLogs/EnterpriselmsSystemadminAuditlogsController";
import { EnterpriselmsSystemadminSessionsController } from "./controllers/enterpriseLms/systemAdmin/sessions/EnterpriselmsSystemadminSessionsController";
import { EnterpriselmsOrganizationadminSessionsController } from "./controllers/enterpriseLms/organizationAdmin/sessions/EnterpriselmsOrganizationadminSessionsController";
import { EnterpriselmsDepartmentmanagerSessionsController } from "./controllers/enterpriseLms/departmentManager/sessions/EnterpriselmsDepartmentmanagerSessionsController";
import { EnterpriselmsContentcreatorinstructorSessionsController } from "./controllers/enterpriseLms/contentCreatorInstructor/sessions/EnterpriselmsContentcreatorinstructorSessionsController";
import { EnterpriselmsSystemadminRolepermissionsController } from "./controllers/enterpriseLms/systemAdmin/rolePermissions/EnterpriselmsSystemadminRolepermissionsController";
import { EnterpriselmsOrganizationadminRolepermissionsController } from "./controllers/enterpriseLms/organizationAdmin/rolePermissions/EnterpriselmsOrganizationadminRolepermissionsController";
import { EnterpriselmsDepartmentmanagerRolepermissionsController } from "./controllers/enterpriseLms/departmentManager/rolePermissions/EnterpriselmsDepartmentmanagerRolepermissionsController";
import { EnterpriselmsContentcreatorinstructorRolepermissionsController } from "./controllers/enterpriseLms/contentCreatorInstructor/rolePermissions/EnterpriselmsContentcreatorinstructorRolepermissionsController";
import { EnterpriselmsSystemadminIntegrationsettingsController } from "./controllers/enterpriseLms/systemAdmin/integrationSettings/EnterpriselmsSystemadminIntegrationsettingsController";
import { EnterpriselmsSystemadminNotificationlogsController } from "./controllers/enterpriseLms/systemAdmin/notificationLogs/EnterpriselmsSystemadminNotificationlogsController";
import { EnterpriselmsSystemadminPaymenttransactionsController } from "./controllers/enterpriseLms/systemAdmin/paymentTransactions/EnterpriselmsSystemadminPaymenttransactionsController";
import { EnterpriselmsCorporatelearnerPaymenttransactionsController } from "./controllers/enterpriseLms/corporateLearner/paymentTransactions/EnterpriselmsCorporatelearnerPaymenttransactionsController";
import { EnterpriselmsExternallearnerPaymenttransactionsController } from "./controllers/enterpriseLms/externalLearner/paymentTransactions/EnterpriselmsExternallearnerPaymenttransactionsController";
import { EnterpriselmsGuestPaymenttransactionsController } from "./controllers/enterpriseLms/guest/paymentTransactions/EnterpriselmsGuestPaymenttransactionsController";
import { EnterpriselmsSystemadminPerformancemetricsController } from "./controllers/enterpriseLms/systemAdmin/performanceMetrics/EnterpriselmsSystemadminPerformancemetricsController";
import { EnterpriselmsOrganizationadminPerformancemetricsController } from "./controllers/enterpriseLms/organizationAdmin/performanceMetrics/EnterpriselmsOrganizationadminPerformancemetricsController";
import { EnterpriselmsSystemadminSecurityauditlogsController } from "./controllers/enterpriseLms/systemAdmin/securityAuditLogs/EnterpriselmsSystemadminSecurityauditlogsController";
import { EnterpriselmsSystemadminBackuprecordsController } from "./controllers/enterpriseLms/systemAdmin/backupRecords/EnterpriselmsSystemadminBackuprecordsController";
import { EnterpriselmsSystemadminSystemadminsController } from "./controllers/enterpriseLms/systemAdmin/systemadmins/EnterpriselmsSystemadminSystemadminsController";
import { EnterpriselmsSystemadminOrganizationadminsController } from "./controllers/enterpriseLms/systemAdmin/organizationadmins/EnterpriselmsSystemadminOrganizationadminsController";
import { EnterpriselmsOrganizationadminOrganizationadminsController } from "./controllers/enterpriseLms/organizationAdmin/organizationadmins/EnterpriselmsOrganizationadminOrganizationadminsController";
import { EnterpriselmsOrganizationadminDepartmentmanagersController } from "./controllers/enterpriseLms/organizationAdmin/departmentmanagers/EnterpriselmsOrganizationadminDepartmentmanagersController";
import { EnterpriselmsDepartmentmanagerDepartmentmanagersController } from "./controllers/enterpriseLms/departmentManager/departmentmanagers/EnterpriselmsDepartmentmanagerDepartmentmanagersController";
import { EnterpriselmsOrganizationadminContentcreatorinstructorsController } from "./controllers/enterpriseLms/organizationAdmin/contentcreatorinstructors/EnterpriselmsOrganizationadminContentcreatorinstructorsController";
import { EnterpriselmsSystemadminContentcreatorinstructorsController } from "./controllers/enterpriseLms/systemAdmin/contentcreatorinstructors/EnterpriselmsSystemadminContentcreatorinstructorsController";
import { EnterpriselmsOrganizationadminCorporatelearnersController } from "./controllers/enterpriseLms/organizationAdmin/corporatelearners/EnterpriselmsOrganizationadminCorporatelearnersController";
import { EnterpriselmsSystemadminCorporatelearnersController } from "./controllers/enterpriseLms/systemAdmin/corporatelearners/EnterpriselmsSystemadminCorporatelearnersController";
import { EnterpriselmsSystemadminExternallearnersController } from "./controllers/enterpriseLms/systemAdmin/externallearners/EnterpriselmsSystemadminExternallearnersController";
import { EnterpriselmsOrganizationadminExternallearnersController } from "./controllers/enterpriseLms/organizationAdmin/externallearners/EnterpriselmsOrganizationadminExternallearnersController";
import { EnterpriselmsExternallearnersController } from "./controllers/enterpriseLms/externallearners/EnterpriselmsExternallearnersController";
import { EnterpriselmsExternallearnerExternallearnersController } from "./controllers/enterpriseLms/externalLearner/externallearners/EnterpriselmsExternallearnerExternallearnersController";
import { EnterpriselmsOrganizationadminGuestsController } from "./controllers/enterpriseLms/organizationAdmin/guests/EnterpriselmsOrganizationadminGuestsController";
import { EnterpriselmsGuestGuestsController } from "./controllers/enterpriseLms/guest/guests/EnterpriselmsGuestGuestsController";
import { EnterpriselmsCorporatelearnerContentsController } from "./controllers/enterpriseLms/corporateLearner/contents/EnterpriselmsCorporatelearnerContentsController";
import { EnterpriselmsContentcreatorinstructorContentsController } from "./controllers/enterpriseLms/contentCreatorInstructor/contents/EnterpriselmsContentcreatorinstructorContentsController";
import { EnterpriselmsSystemadminContentsController } from "./controllers/enterpriseLms/systemAdmin/contents/EnterpriselmsSystemadminContentsController";
import { EnterpriselmsOrganizationadminContentsController } from "./controllers/enterpriseLms/organizationAdmin/contents/EnterpriselmsOrganizationadminContentsController";
import { EnterpriselmsSystemadminContentsContentversionsController } from "./controllers/enterpriseLms/systemAdmin/contents/contentVersions/EnterpriselmsSystemadminContentsContentversionsController";
import { EnterpriselmsOrganizationadminContentsContentversionsController } from "./controllers/enterpriseLms/organizationAdmin/contents/contentVersions/EnterpriselmsOrganizationadminContentsContentversionsController";
import { EnterpriselmsSystemadminContentsContentapprovalworkflowsController } from "./controllers/enterpriseLms/systemAdmin/contents/contentApprovalWorkflows/EnterpriselmsSystemadminContentsContentapprovalworkflowsController";
import { EnterpriselmsOrganizationadminContentsContentapprovalworkflowsController } from "./controllers/enterpriseLms/organizationAdmin/contents/contentApprovalWorkflows/EnterpriselmsOrganizationadminContentsContentapprovalworkflowsController";
import { EnterpriselmsCorporatelearnerContentsContentlocalizationsController } from "./controllers/enterpriseLms/corporateLearner/contents/contentLocalizations/EnterpriselmsCorporatelearnerContentsContentlocalizationsController";
import { EnterpriselmsContentcreatorinstructorContentsContentlocalizationsController } from "./controllers/enterpriseLms/contentCreatorInstructor/contents/contentLocalizations/EnterpriselmsContentcreatorinstructorContentsContentlocalizationsController";
import { EnterpriselmsOrganizationadminContentsContentlocalizationsController } from "./controllers/enterpriseLms/organizationAdmin/contents/contentLocalizations/EnterpriselmsOrganizationadminContentsContentlocalizationsController";
import { EnterpriselmsSystemadminContentsContentlocalizationsController } from "./controllers/enterpriseLms/systemAdmin/contents/contentLocalizations/EnterpriselmsSystemadminContentsContentlocalizationsController";
import { EnterpriselmsOrganizationadminContenttagsController } from "./controllers/enterpriseLms/organizationAdmin/contentTags/EnterpriselmsOrganizationadminContenttagsController";
import { EnterpriselmsContentcreatorinstructorContenttagsController } from "./controllers/enterpriseLms/contentCreatorInstructor/contentTags/EnterpriselmsContentcreatorinstructorContenttagsController";
import { EnterpriselmsSystemadminContenttagsController } from "./controllers/enterpriseLms/systemAdmin/contentTags/EnterpriselmsSystemadminContenttagsController";
import { EnterpriselmsSystemadminContenttagsChildtagsController } from "./controllers/enterpriseLms/systemAdmin/contentTags/childTags/EnterpriselmsSystemadminContenttagsChildtagsController";
import { EnterpriselmsOrganizationadminContenttagsChildtagsController } from "./controllers/enterpriseLms/organizationAdmin/contentTags/childTags/EnterpriselmsOrganizationadminContenttagsChildtagsController";
import { EnterpriselmsContentcreatorinstructorContenttagsChildtagsController } from "./controllers/enterpriseLms/contentCreatorInstructor/contentTags/childTags/EnterpriselmsContentcreatorinstructorContenttagsChildtagsController";
import { EnterpriselmsSystemadminLearningpathsController } from "./controllers/enterpriseLms/systemAdmin/learningPaths/EnterpriselmsSystemadminLearningpathsController";
import { EnterpriselmsOrganizationadminLearningpathsController } from "./controllers/enterpriseLms/organizationAdmin/learningPaths/EnterpriselmsOrganizationadminLearningpathsController";
import { EnterpriselmsContentcreatorinstructorLearningpathsController } from "./controllers/enterpriseLms/contentCreatorInstructor/learningPaths/EnterpriselmsContentcreatorinstructorLearningpathsController";
import { EnterpriselmsCorporatelearnerLearningpathsController } from "./controllers/enterpriseLms/corporateLearner/learningPaths/EnterpriselmsCorporatelearnerLearningpathsController";
import { EnterpriselmsCorporatelearnerLearningpathsLearningpathitemsController } from "./controllers/enterpriseLms/corporateLearner/learningPaths/learningPathItems/EnterpriselmsCorporatelearnerLearningpathsLearningpathitemsController";
import { EnterpriselmsContentcreatorinstructorLearningpathsLearningpathitemsController } from "./controllers/enterpriseLms/contentCreatorInstructor/learningPaths/learningPathItems/EnterpriselmsContentcreatorinstructorLearningpathsLearningpathitemsController";
import { EnterpriselmsOrganizationadminLearningpathsLearningpathitemsController } from "./controllers/enterpriseLms/organizationAdmin/learningPaths/learningPathItems/EnterpriselmsOrganizationadminLearningpathsLearningpathitemsController";
import { EnterpriselmsDepartmentmanagerLearningpathsLearningpathitemsController } from "./controllers/enterpriseLms/departmentManager/learningPaths/learningPathItems/EnterpriselmsDepartmentmanagerLearningpathsLearningpathitemsController";
import { EnterpriselmsOrganizationadminCertificationsController } from "./controllers/enterpriseLms/organizationAdmin/certifications/EnterpriselmsOrganizationadminCertificationsController";
import { EnterpriselmsDepartmentmanagerCertificationsController } from "./controllers/enterpriseLms/departmentManager/certifications/EnterpriselmsDepartmentmanagerCertificationsController";
import { EnterpriselmsOrganizationadminCertificationsCertificationexpirationsController } from "./controllers/enterpriseLms/organizationAdmin/certifications/certificationExpirations/EnterpriselmsOrganizationadminCertificationsCertificationexpirationsController";
import { EnterpriselmsOrganizationadminCompetenciesController } from "./controllers/enterpriseLms/organizationAdmin/competencies/EnterpriselmsOrganizationadminCompetenciesController";
import { EnterpriselmsSystemadminBlendedlearningsessionsController } from "./controllers/enterpriseLms/systemAdmin/blendedLearningSessions/EnterpriselmsSystemadminBlendedlearningsessionsController";
import { EnterpriselmsOrganizationadminBlendedlearningsessionsController } from "./controllers/enterpriseLms/organizationAdmin/blendedLearningSessions/EnterpriselmsOrganizationadminBlendedlearningsessionsController";
import { EnterpriselmsDepartmentmanagerBlendedlearningsessionsController } from "./controllers/enterpriseLms/departmentManager/blendedLearningSessions/EnterpriselmsDepartmentmanagerBlendedlearningsessionsController";
import { EnterpriselmsContentcreatorinstructorBlendedlearningsessionsController } from "./controllers/enterpriseLms/contentCreatorInstructor/blendedLearningSessions/EnterpriselmsContentcreatorinstructorBlendedlearningsessionsController";
import { EnterpriselmsCorporatelearnerBlendedlearningsessionsController } from "./controllers/enterpriseLms/corporateLearner/blendedLearningSessions/EnterpriselmsCorporatelearnerBlendedlearningsessionsController";
import { EnterpriselmsExternallearnerBlendedlearningsessionsController } from "./controllers/enterpriseLms/externalLearner/blendedLearningSessions/EnterpriselmsExternallearnerBlendedlearningsessionsController";
import { EnterpriselmsGuestBlendedlearningsessionsController } from "./controllers/enterpriseLms/guest/blendedLearningSessions/EnterpriselmsGuestBlendedlearningsessionsController";
import { EnterpriselmsSystemadminAssessmentsController } from "./controllers/enterpriseLms/systemAdmin/assessments/EnterpriselmsSystemadminAssessmentsController";
import { EnterpriselmsOrganizationadminAssessmentsController } from "./controllers/enterpriseLms/organizationAdmin/assessments/EnterpriselmsOrganizationadminAssessmentsController";
import { EnterpriselmsContentcreatorinstructorAssessmentsController } from "./controllers/enterpriseLms/contentCreatorInstructor/assessments/EnterpriselmsContentcreatorinstructorAssessmentsController";
import { EnterpriselmsSystemadminAssessmentsQuestionsController } from "./controllers/enterpriseLms/systemAdmin/assessments/questions/EnterpriselmsSystemadminAssessmentsQuestionsController";
import { EnterpriselmsOrganizationadminAssessmentsQuestionsController } from "./controllers/enterpriseLms/organizationAdmin/assessments/questions/EnterpriselmsOrganizationadminAssessmentsQuestionsController";
import { EnterpriselmsContentcreatorinstructorAssessmentsQuestionsController } from "./controllers/enterpriseLms/contentCreatorInstructor/assessments/questions/EnterpriselmsContentcreatorinstructorAssessmentsQuestionsController";
import { EnterpriselmsContentcreatorinstructorAssessmentsResultsController } from "./controllers/enterpriseLms/contentCreatorInstructor/assessments/results/EnterpriselmsContentcreatorinstructorAssessmentsResultsController";
import { EnterpriselmsOrganizationadminAssessmentsResultsController } from "./controllers/enterpriseLms/organizationAdmin/assessments/results/EnterpriselmsOrganizationadminAssessmentsResultsController";
import { EnterpriselmsSystemadminAssessmentsResultsController } from "./controllers/enterpriseLms/systemAdmin/assessments/results/EnterpriselmsSystemadminAssessmentsResultsController";
import { EnterpriselmsCorporatelearnerAssessmentsResultsController } from "./controllers/enterpriseLms/corporateLearner/assessments/results/EnterpriselmsCorporatelearnerAssessmentsResultsController";
import { EnterpriselmsSystemadminAssessmentsProctoredexamsController } from "./controllers/enterpriseLms/systemAdmin/assessments/proctoredExams/EnterpriselmsSystemadminAssessmentsProctoredexamsController";
import { EnterpriselmsOrganizationadminAssessmentsProctoredexamsController } from "./controllers/enterpriseLms/organizationAdmin/assessments/proctoredExams/EnterpriselmsOrganizationadminAssessmentsProctoredexamsController";
import { EnterpriselmsDepartmentmanagerAssessmentsProctoredexamsController } from "./controllers/enterpriseLms/departmentManager/assessments/proctoredExams/EnterpriselmsDepartmentmanagerAssessmentsProctoredexamsController";
import { EnterpriselmsContentcreatorinstructorAssessmentsProctoredexamsController } from "./controllers/enterpriseLms/contentCreatorInstructor/assessments/proctoredExams/EnterpriselmsContentcreatorinstructorAssessmentsProctoredexamsController";
import { EnterpriselmsCorporatelearnerAssessmentsProctoredexamsController } from "./controllers/enterpriseLms/corporateLearner/assessments/proctoredExams/EnterpriselmsCorporatelearnerAssessmentsProctoredexamsController";
import { EnterpriselmsExternallearnerAssessmentsProctoredexamsController } from "./controllers/enterpriseLms/externalLearner/assessments/proctoredExams/EnterpriselmsExternallearnerAssessmentsProctoredexamsController";
import { EnterpriselmsGuestAssessmentsProctoredexamsController } from "./controllers/enterpriseLms/guest/assessments/proctoredExams/EnterpriselmsGuestAssessmentsProctoredexamsController";
import { EnterpriselmsSystemadminAnalyticsreportsController } from "./controllers/enterpriseLms/systemAdmin/analyticsReports/EnterpriselmsSystemadminAnalyticsreportsController";
import { EnterpriselmsOrganizationadminAnalyticsreportsController } from "./controllers/enterpriseLms/organizationAdmin/analyticsReports/EnterpriselmsOrganizationadminAnalyticsreportsController";
import { EnterpriselmsDepartmentmanagerAnalyticsreportsController } from "./controllers/enterpriseLms/departmentManager/analyticsReports/EnterpriselmsDepartmentmanagerAnalyticsreportsController";
import { EnterpriselmsContentcreatorinstructorAnalyticsreportsController } from "./controllers/enterpriseLms/contentCreatorInstructor/analyticsReports/EnterpriselmsContentcreatorinstructorAnalyticsreportsController";
import { EnterpriselmsForumsController } from "./controllers/enterpriseLms/forums/EnterpriselmsForumsController";
import { EnterpriselmsOrganizationadminForumsController } from "./controllers/enterpriseLms/organizationAdmin/forums/EnterpriselmsOrganizationadminForumsController";
import { EnterpriselmsOrganizationadminForumsForumthreadsController } from "./controllers/enterpriseLms/organizationAdmin/forums/forumThreads/EnterpriselmsOrganizationadminForumsForumthreadsController";
import { EnterpriselmsContentcreatorinstructorForumsForumthreadsController } from "./controllers/enterpriseLms/contentCreatorInstructor/forums/forumThreads/EnterpriselmsContentcreatorinstructorForumsForumthreadsController";
import { EnterpriselmsSystemadminForumsForumthreadsController } from "./controllers/enterpriseLms/systemAdmin/forums/forumThreads/EnterpriselmsSystemadminForumsForumthreadsController";
import { EnterpriselmsDepartmentmanagerForumsForumthreadsController } from "./controllers/enterpriseLms/departmentManager/forums/forumThreads/EnterpriselmsDepartmentmanagerForumsForumthreadsController";
import { EnterpriselmsCorporatelearnerForumsForumthreadsController } from "./controllers/enterpriseLms/corporateLearner/forums/forumThreads/EnterpriselmsCorporatelearnerForumsForumthreadsController";
import { EnterpriselmsExternallearnerForumsForumthreadsController } from "./controllers/enterpriseLms/externalLearner/forums/forumThreads/EnterpriselmsExternallearnerForumsForumthreadsController";
import { EnterpriselmsGuestForumsForumthreadsController } from "./controllers/enterpriseLms/guest/forums/forumThreads/EnterpriselmsGuestForumsForumthreadsController";
import { EnterpriselmsCorporatelearnerForumsForumthreadsForumpostsController } from "./controllers/enterpriseLms/corporateLearner/forums/forumThreads/forumPosts/EnterpriselmsCorporatelearnerForumsForumthreadsForumpostsController";
import { EnterpriselmsOrganizationadminForumsForumthreadsForumpostsController } from "./controllers/enterpriseLms/organizationAdmin/forums/forumThreads/forumPosts/EnterpriselmsOrganizationadminForumsForumthreadsForumpostsController";
import { EnterpriselmsDepartmentmanagerForumsForumthreadsForumpostsController } from "./controllers/enterpriseLms/departmentManager/forums/forumThreads/forumPosts/EnterpriselmsDepartmentmanagerForumsForumthreadsForumpostsController";
import { EnterpriselmsCorporatelearnerDirectmessagesController } from "./controllers/enterpriseLms/corporateLearner/directMessages/EnterpriselmsCorporatelearnerDirectmessagesController";
import { EnterpriselmsExternallearnerDirectmessagesController } from "./controllers/enterpriseLms/externalLearner/directMessages/EnterpriselmsExternallearnerDirectmessagesController";
import { EnterpriselmsCorporatelearnerVirtualclassroomsController } from "./controllers/enterpriseLms/corporateLearner/virtualClassrooms/EnterpriselmsCorporatelearnerVirtualclassroomsController";
import { EnterpriselmsContentcreatorinstructorVirtualclassroomsController } from "./controllers/enterpriseLms/contentCreatorInstructor/virtualClassrooms/EnterpriselmsContentcreatorinstructorVirtualclassroomsController";
import { EnterpriselmsCorporatelearnerGroupprojectsController } from "./controllers/enterpriseLms/corporateLearner/groupProjects/EnterpriselmsCorporatelearnerGroupprojectsController";
import { EnterpriselmsOrganizationadminAnnouncementsController } from "./controllers/enterpriseLms/organizationAdmin/announcements/EnterpriselmsOrganizationadminAnnouncementsController";
import { EnterpriselmsCorporatelearnerEnrollmentsController } from "./controllers/enterpriseLms/corporateLearner/enrollments/EnterpriselmsCorporatelearnerEnrollmentsController";
import { EnterpriselmsSystemadminEnrollmentsController } from "./controllers/enterpriseLms/systemAdmin/enrollments/EnterpriselmsSystemadminEnrollmentsController";
import { EnterpriselmsOrganizationadminEnrollmentsController } from "./controllers/enterpriseLms/organizationAdmin/enrollments/EnterpriselmsOrganizationadminEnrollmentsController";
import { EnterpriselmsDepartmentmanagerEnrollmentsController } from "./controllers/enterpriseLms/departmentManager/enrollments/EnterpriselmsDepartmentmanagerEnrollmentsController";
import { EnterpriselmsSystemadminEnrollmentsEnrollmentprerequisitesController } from "./controllers/enterpriseLms/systemAdmin/enrollments/enrollmentPrerequisites/EnterpriselmsSystemadminEnrollmentsEnrollmentprerequisitesController";
import { EnterpriselmsOrganizationadminEnrollmentsEnrollmentprerequisitesController } from "./controllers/enterpriseLms/organizationAdmin/enrollments/enrollmentPrerequisites/EnterpriselmsOrganizationadminEnrollmentsEnrollmentprerequisitesController";
import { EnterpriselmsDepartmentmanagerEnrollmentsEnrollmentprerequisitesController } from "./controllers/enterpriseLms/departmentManager/enrollments/enrollmentPrerequisites/EnterpriselmsDepartmentmanagerEnrollmentsEnrollmentprerequisitesController";
import { EnterpriselmsOrganizationadminCertificateissuancesController } from "./controllers/enterpriseLms/organizationAdmin/certificateIssuances/EnterpriselmsOrganizationadminCertificateissuancesController";
import { EnterpriselmsSystemadminCertificateissuancesController } from "./controllers/enterpriseLms/systemAdmin/certificateIssuances/EnterpriselmsSystemadminCertificateissuancesController";
import { EnterpriselmsOrganizationadminContentaccesscontrolsController } from "./controllers/enterpriseLms/organizationAdmin/contentAccessControls/EnterpriselmsOrganizationadminContentaccesscontrolsController";
import { EnterpriselmsSystemadminContentaccesscontrolsController } from "./controllers/enterpriseLms/systemAdmin/contentAccessControls/EnterpriselmsSystemadminContentaccesscontrolsController";
import { EnterpriselmsCorporatelearnerProgresstrackingController } from "./controllers/enterpriseLms/corporateLearner/progressTracking/EnterpriselmsCorporatelearnerProgresstrackingController";
import { EnterpriselmsOrganizationadminCompliancerecordsController } from "./controllers/enterpriseLms/organizationAdmin/complianceRecords/EnterpriselmsOrganizationadminCompliancerecordsController";
import { EnterpriselmsCorporatelearnerCompliancerecordsController } from "./controllers/enterpriseLms/corporateLearner/complianceRecords/EnterpriselmsCorporatelearnerCompliancerecordsController";

@Module({
  controllers: [
    AuthSystemadminController,
    AuthOrganizationadminController,
    AuthDepartmentmanagerController,
    AuthContentcreatorinstructorController,
    AuthCorporatelearnerController,
    AuthExternallearnerJoinController,
    AuthExternallearnerRefreshController,
    AuthGuestController,
    EnterpriselmsSystemadminTenantsController,
    EnterpriselmsOrganizationadminTenantsTenantsettingsController,
    EnterpriselmsSystemadminTenantsTenantsettingsController,
    EnterpriselmsSystemadminSystemconfigurationsController,
    EnterpriselmsSystemadminAuditlogsController,
    EnterpriselmsSystemadminSessionsController,
    EnterpriselmsOrganizationadminSessionsController,
    EnterpriselmsDepartmentmanagerSessionsController,
    EnterpriselmsContentcreatorinstructorSessionsController,
    EnterpriselmsSystemadminRolepermissionsController,
    EnterpriselmsOrganizationadminRolepermissionsController,
    EnterpriselmsDepartmentmanagerRolepermissionsController,
    EnterpriselmsContentcreatorinstructorRolepermissionsController,
    EnterpriselmsSystemadminIntegrationsettingsController,
    EnterpriselmsSystemadminNotificationlogsController,
    EnterpriselmsSystemadminPaymenttransactionsController,
    EnterpriselmsCorporatelearnerPaymenttransactionsController,
    EnterpriselmsExternallearnerPaymenttransactionsController,
    EnterpriselmsGuestPaymenttransactionsController,
    EnterpriselmsSystemadminPerformancemetricsController,
    EnterpriselmsOrganizationadminPerformancemetricsController,
    EnterpriselmsSystemadminSecurityauditlogsController,
    EnterpriselmsSystemadminBackuprecordsController,
    EnterpriselmsSystemadminSystemadminsController,
    EnterpriselmsSystemadminOrganizationadminsController,
    EnterpriselmsOrganizationadminOrganizationadminsController,
    EnterpriselmsOrganizationadminDepartmentmanagersController,
    EnterpriselmsDepartmentmanagerDepartmentmanagersController,
    EnterpriselmsOrganizationadminContentcreatorinstructorsController,
    EnterpriselmsSystemadminContentcreatorinstructorsController,
    EnterpriselmsOrganizationadminCorporatelearnersController,
    EnterpriselmsSystemadminCorporatelearnersController,
    EnterpriselmsSystemadminExternallearnersController,
    EnterpriselmsOrganizationadminExternallearnersController,
    EnterpriselmsExternallearnersController,
    EnterpriselmsExternallearnerExternallearnersController,
    EnterpriselmsOrganizationadminGuestsController,
    EnterpriselmsGuestGuestsController,
    EnterpriselmsCorporatelearnerContentsController,
    EnterpriselmsContentcreatorinstructorContentsController,
    EnterpriselmsSystemadminContentsController,
    EnterpriselmsOrganizationadminContentsController,
    EnterpriselmsSystemadminContentsContentversionsController,
    EnterpriselmsOrganizationadminContentsContentversionsController,
    EnterpriselmsSystemadminContentsContentapprovalworkflowsController,
    EnterpriselmsOrganizationadminContentsContentapprovalworkflowsController,
    EnterpriselmsCorporatelearnerContentsContentlocalizationsController,
    EnterpriselmsContentcreatorinstructorContentsContentlocalizationsController,
    EnterpriselmsOrganizationadminContentsContentlocalizationsController,
    EnterpriselmsSystemadminContentsContentlocalizationsController,
    EnterpriselmsOrganizationadminContenttagsController,
    EnterpriselmsContentcreatorinstructorContenttagsController,
    EnterpriselmsSystemadminContenttagsController,
    EnterpriselmsSystemadminContenttagsChildtagsController,
    EnterpriselmsOrganizationadminContenttagsChildtagsController,
    EnterpriselmsContentcreatorinstructorContenttagsChildtagsController,
    EnterpriselmsSystemadminLearningpathsController,
    EnterpriselmsOrganizationadminLearningpathsController,
    EnterpriselmsContentcreatorinstructorLearningpathsController,
    EnterpriselmsCorporatelearnerLearningpathsController,
    EnterpriselmsCorporatelearnerLearningpathsLearningpathitemsController,
    EnterpriselmsContentcreatorinstructorLearningpathsLearningpathitemsController,
    EnterpriselmsOrganizationadminLearningpathsLearningpathitemsController,
    EnterpriselmsDepartmentmanagerLearningpathsLearningpathitemsController,
    EnterpriselmsOrganizationadminCertificationsController,
    EnterpriselmsDepartmentmanagerCertificationsController,
    EnterpriselmsOrganizationadminCertificationsCertificationexpirationsController,
    EnterpriselmsOrganizationadminCompetenciesController,
    EnterpriselmsSystemadminBlendedlearningsessionsController,
    EnterpriselmsOrganizationadminBlendedlearningsessionsController,
    EnterpriselmsDepartmentmanagerBlendedlearningsessionsController,
    EnterpriselmsContentcreatorinstructorBlendedlearningsessionsController,
    EnterpriselmsCorporatelearnerBlendedlearningsessionsController,
    EnterpriselmsExternallearnerBlendedlearningsessionsController,
    EnterpriselmsGuestBlendedlearningsessionsController,
    EnterpriselmsSystemadminAssessmentsController,
    EnterpriselmsOrganizationadminAssessmentsController,
    EnterpriselmsContentcreatorinstructorAssessmentsController,
    EnterpriselmsSystemadminAssessmentsQuestionsController,
    EnterpriselmsOrganizationadminAssessmentsQuestionsController,
    EnterpriselmsContentcreatorinstructorAssessmentsQuestionsController,
    EnterpriselmsContentcreatorinstructorAssessmentsResultsController,
    EnterpriselmsOrganizationadminAssessmentsResultsController,
    EnterpriselmsSystemadminAssessmentsResultsController,
    EnterpriselmsCorporatelearnerAssessmentsResultsController,
    EnterpriselmsSystemadminAssessmentsProctoredexamsController,
    EnterpriselmsOrganizationadminAssessmentsProctoredexamsController,
    EnterpriselmsDepartmentmanagerAssessmentsProctoredexamsController,
    EnterpriselmsContentcreatorinstructorAssessmentsProctoredexamsController,
    EnterpriselmsCorporatelearnerAssessmentsProctoredexamsController,
    EnterpriselmsExternallearnerAssessmentsProctoredexamsController,
    EnterpriselmsGuestAssessmentsProctoredexamsController,
    EnterpriselmsSystemadminAnalyticsreportsController,
    EnterpriselmsOrganizationadminAnalyticsreportsController,
    EnterpriselmsDepartmentmanagerAnalyticsreportsController,
    EnterpriselmsContentcreatorinstructorAnalyticsreportsController,
    EnterpriselmsForumsController,
    EnterpriselmsOrganizationadminForumsController,
    EnterpriselmsOrganizationadminForumsForumthreadsController,
    EnterpriselmsContentcreatorinstructorForumsForumthreadsController,
    EnterpriselmsSystemadminForumsForumthreadsController,
    EnterpriselmsDepartmentmanagerForumsForumthreadsController,
    EnterpriselmsCorporatelearnerForumsForumthreadsController,
    EnterpriselmsExternallearnerForumsForumthreadsController,
    EnterpriselmsGuestForumsForumthreadsController,
    EnterpriselmsCorporatelearnerForumsForumthreadsForumpostsController,
    EnterpriselmsOrganizationadminForumsForumthreadsForumpostsController,
    EnterpriselmsDepartmentmanagerForumsForumthreadsForumpostsController,
    EnterpriselmsCorporatelearnerDirectmessagesController,
    EnterpriselmsExternallearnerDirectmessagesController,
    EnterpriselmsCorporatelearnerVirtualclassroomsController,
    EnterpriselmsContentcreatorinstructorVirtualclassroomsController,
    EnterpriselmsCorporatelearnerGroupprojectsController,
    EnterpriselmsOrganizationadminAnnouncementsController,
    EnterpriselmsCorporatelearnerEnrollmentsController,
    EnterpriselmsSystemadminEnrollmentsController,
    EnterpriselmsOrganizationadminEnrollmentsController,
    EnterpriselmsDepartmentmanagerEnrollmentsController,
    EnterpriselmsSystemadminEnrollmentsEnrollmentprerequisitesController,
    EnterpriselmsOrganizationadminEnrollmentsEnrollmentprerequisitesController,
    EnterpriselmsDepartmentmanagerEnrollmentsEnrollmentprerequisitesController,
    EnterpriselmsOrganizationadminCertificateissuancesController,
    EnterpriselmsSystemadminCertificateissuancesController,
    EnterpriselmsOrganizationadminContentaccesscontrolsController,
    EnterpriselmsSystemadminContentaccesscontrolsController,
    EnterpriselmsCorporatelearnerProgresstrackingController,
    EnterpriselmsOrganizationadminCompliancerecordsController,
    EnterpriselmsCorporatelearnerCompliancerecordsController,
  ],
})
export class MyModule {}
