import { tags } from "typia";

/**
 * Announcement messages sent to groups within tenants. Announcements have a
 * title, body, target audience description, and status tracking including
 * pipeline status such as draft, sent, or archived. They support soft deletion
 * and timestamps for creation and update. Announcements help communicate
 * important information across the enterprise LMS ecosystem.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEnterpriseLmsAnnouncement = {
  /** Unique identifier for the announcement. */
  id: string & tags.Format<"uuid">;

  /** Tenant identifier owning this announcement. */
  tenant_id: string & tags.Format<"uuid">;

  /** Creator user (organization/department admin) identifier. */
  creator_id: string & tags.Format<"uuid">;

  /** Title of the announcement. */
  title: string;

  /** Body content of the announcement. */
  body: string;

  /**
   * Description of the target audience for the announcement.
   *
   * Optional field describing who is targeted.
   */
  target_audience_description?: string | null | undefined;

  /**
   * The current status of the announcement, e.g. 'draft', 'sent', 'archived'.
   *
   * Must be an exact allowed string value.
   */
  status: string;

  /**
   * Creation timestamp of the announcement.
   *
   * ISO 8601 formatted date-time string.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Last update timestamp.
   *
   * ISO 8601 formatted date-time string.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Optional soft deletion timestamp.
   *
   * Null means active; ISO 8601 datetime if deleted.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IEnterpriseLmsAnnouncement {
  /** Search and pagination parameters for tenant announcements */
  export type IRequest = {
    /** Tenant ID filter for announcements (UUID) */
    tenant_id?: (string & tags.Format<"uuid">) | undefined;

    /** Creation date filter start (ISO 8601) */
    created_at_from?: (string & tags.Format<"date-time">) | null | undefined;

    /** Creation date filter end (ISO 8601) */
    created_at_to?: (string & tags.Format<"date-time">) | null | undefined;

    /** Filter by status */
    status?: string | null | undefined;

    /** Title or partial match filter */
    title?: string | null | undefined;

    /** Pagination page number */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /** Pagination limit of items per page */
    limit?: (number & tags.Type<"int32"> & tags.Minimum<1>) | null | undefined;

    /** Sort order: 'asc' or 'desc' */
    order?: "asc" | "desc" | null | undefined;
  };

  /**
   * Request body for creating a new announcement record within a tenant
   * organization.
   *
   * Includes title, body, target audience, and pipeline status.
   *
   * Tenant ID and creator ID are required for attribution and security.
   */
  export type ICreate = {
    /** Tenant identifier owning the announcement. */
    tenant_id: string & tags.Format<"uuid">;

    /** Creator user (organization/department admin) identifier. */
    creator_id: string & tags.Format<"uuid">;

    /** Title of the announcement. */
    title: string;

    /** Body content of the announcement. */
    body: string;

    /**
     * Description of the target audience for the announcement.
     *
     * Optional and nullable.
     */
    target_audience_description?: string | null | undefined;

    /**
     * Status must be set explicitly. Required string denoting announcement
     * state.
     */
    status: string;
  };

  /**
   * Update an existing announcement by its unique identifier within the
   * enterprise LMS tenant context. It modifies forum metadata such as name
   * and description, ensuring the tenant and owner associations remain
   * consistent. The operation updates the 'enterprise_lms_announcements'
   * table, enforcing unique name constraints per tenant and preserving data
   * isolation. Authorization to modify is restricted to organization
   * administrators maintaining security and correct ownership.
   */
  export type IUpdate = {
    /** Title of the announcement */
    title: string;

    /** Content body of the announcement */
    body: string;

    /** Description of the target audience for the announcement, optional */
    target_audience_description?: string | null | undefined;

    /** Status of the announcement, e.g., 'draft', 'sent', 'archived' */
    status: string;
  };
}
