import { IPage } from "./IPage";
import { IEnterpriseLmsAssessmentResult } from "./IEnterpriseLmsAssessmentResult";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageIEnterpriseLmsAssessmentResult = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: IEnterpriseLmsAssessmentResult[];
};
