import { tags } from "typia";

/**
 * Analytics KPI widget representing key business metrics linked to a UI widget.
 * Stores the JSON configuration of the widget's data sources, aggregation
 * methods, and display options. Tracks standard timestamps for creation,
 * update, and soft deletion.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IFlexOfficeKpiWidget = {
  /** Primary Key. Unique identifier for the KPI widget record. */
  id: string & tags.Format<"uuid">;

  /** Foreign key to the FlexOffice UI widget that this KPI widget represents. */
  flex_office_widget_id: string & tags.Format<"uuid">;

  /**
   * JSON string specifying data queries, aggregation methods, and display
   * options.
   */
  config_json: string;

  /** Creation timestamp when this KPI widget was created in the system. */
  created_at: string & tags.Format<"date-time">;

  /** Last update timestamp when this KPI widget was last updated. */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft deletion timestamp. Nullable timestamp indicating if the KPI widget
   * has been deleted.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IFlexOfficeKpiWidget {
  /** Request body for creating a new KPI widget. */
  export type ICreate = {
    /** Foreign key to the FlexOffice UI widget. */
    flex_office_widget_id: string & tags.Format<"uuid">;

    /**
     * JSON configuration specifying data queries, aggregation methods, and
     * display options.
     */
    config_json: string;
  };

  /** Request body for updating an existing KPI widget. */
  export type IUpdate = {
    /** Foreign key to the FlexOffice UI widget. */
    flex_office_widget_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * JSON configuration specifying data queries, aggregation methods, and
     * display options.
     */
    config_json?: string | undefined;
  };
}
