import { tags } from "typia";

/**
 * Captures records of edit conflicts occurring in collaborative editing
 * sessions. Provides historical tracking and audit trails for conflict
 * resolution. Links to the affected page, involved editor, and the conflicting
 * change snapshot. Immutable append-only snapshot table capturing details and
 * timestamps.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IFlexOfficeEditConflict = {
  /** Primary key. */
  id: string & tags.Format<"uuid">;

  /** Referenced page's ID. */
  page_id: string & tags.Format<"uuid">;

  /** Referenced editor user's ID. */
  editor_id: string & tags.Format<"uuid">;

  /** JSON encoded data representing conflicting changes. */
  conflict_data: string;

  /** Timestamp when the conflict record was created. */
  created_at: string & tags.Format<"date-time">;
};
export namespace IFlexOfficeEditConflict {
  /** Request body for paginated search of edit conflicts with filter criteria. */
  export type IRequest = {
    /** Filter by page ID. */
    page_id?: string | null | undefined;

    /** Filter by editor user ID. */
    editor_id?: string | null | undefined;

    /** Search string within conflict data JSON. */
    conflict_data_search?: string | null | undefined;

    /** Filter conflicts created after this date. */
    created_at_from?: string | null | undefined;

    /** Filter conflicts created before this date. */
    created_at_to?: string | null | undefined;

    /** Page number for pagination. */
    page?: (number & tags.Type<"int32">) | null | undefined;

    /** Limit of records per page. */
    limit?: (number & tags.Type<"int32">) | null | undefined;

    /** Field to order results by. */
    orderBy?: string | null | undefined;

    /** Order direction: ascending or descending. */
    orderDir?: "asc" | "desc" | null | undefined;
  };
}
