import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IPoliticalNewsCrawlerGuest } from "../../../structures/IPoliticalNewsCrawlerGuest";

/**
 * Create a temporary guest account and issue JWT tokens. Maps to
 * political_news_crawler_guests table for guest metadata tracking.
 *
 * Provides an endpoint for guest users (unauthenticated) to create a temporary
 * guest account and receive JWT tokens to access public APIs. The join route
 * allows automatically generating guest identifiers without passwords. The
 * response type IPoliticalNewsCrawlerGuest.IAuthorized represents the token
 * response containing temporary guest authentication details and metadata as
 * per the political_news_crawler_guests schema.
 *
 * @param props.connection
 * @param props.body Guest join request payload. For guests, this is typically
 *   empty or minimal since no credentials are needed.
 * @setHeader token.access Authorization
 *
 * @path /auth/guest/join
 * @accessor api.functional.auth.guest.join
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function join(
  connection: IConnection,
  props: join.Props,
): Promise<join.Response> {
  const output: join.Response =
    true === connection.simulate
      ? join.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...join.METADATA,
            path: join.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace join {
  export type Props = {
    /**
     * Guest join request payload. For guests, this is typically empty or
     * minimal since no credentials are needed.
     */
    body: IPoliticalNewsCrawlerGuest.IRequest;
  };
  export type Body = IPoliticalNewsCrawlerGuest.IRequest;
  export type Response = IPoliticalNewsCrawlerGuest.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/guest/join",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/guest/join";
  export const random = (): IPoliticalNewsCrawlerGuest.IAuthorized =>
    typia.random<IPoliticalNewsCrawlerGuest.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: join.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: join.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Refresh guest access tokens securely. Maps to political_news_crawler_guests
 * table for session continuity without login.
 *
 * Refresh temporary JWT tokens for a guest user session. Requires a valid
 * refresh token and issues new tokens with updated expiry.
 *
 * @param props.connection
 * @param props.body Payload containing a refresh token to renew guest JWT
 *   tokens securely.
 * @setHeader token.access Authorization
 *
 * @path /auth/guest/refresh
 * @accessor api.functional.auth.guest.refresh
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function refresh(
  connection: IConnection,
  props: refresh.Props,
): Promise<refresh.Response> {
  const output: refresh.Response =
    true === connection.simulate
      ? refresh.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...refresh.METADATA,
            path: refresh.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace refresh {
  export type Props = {
    /**
     * Payload containing a refresh token to renew guest JWT tokens
     * securely.
     */
    body: IPoliticalNewsCrawlerGuest.IRefresh;
  };
  export type Body = IPoliticalNewsCrawlerGuest.IRefresh;
  export type Response = IPoliticalNewsCrawlerGuest.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/guest/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/guest/refresh";
  export const random = (): IPoliticalNewsCrawlerGuest.IAuthorized =>
    typia.random<IPoliticalNewsCrawlerGuest.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: refresh.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: refresh.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
