import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";

@Controller("/auctionPlatform/admin/chat/messages/:id")
export class AuctionplatformAdminChatMessagesController {
  /**
   * Soft delete a chat message by ID.
   *
   * Delete a chat message by its unique ID.
   *
   * This performs a soft delete by setting the deleted_at timestamp on the
   * auction_platform_chat_messages record. The record remains in the database
   * for auditing but is treated as deleted.
   *
   * Only authorized personnel can perform delete operations on chat messages.
   *
   * Parameters include the message ID path parameter. No request body is
   * needed.
   *
   * Response does not return data, only confirmation of deletion.
   *
   * @param connection
   * @param id Unique identifier of the chat message to delete
   * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
   */
  @TypedRoute.Delete()
  public async eraseChatMessage(
    @TypedParam("id")
    id: string & tags.Format<"uuid">,
  ): Promise<void> {
    id;
    return typia.random<void>();
  }
}
