import { tags } from "typia";

/**
 * Auction platform chat message interface types.
 *
 * Core entity representing chat messages collected via Chijijik API, linked to
 * auction rooms and team leaders. Includes immutable fields managed by the
 * system and mutable fields for chat content.
 *
 * @author AutoBE
 * @namespace IAuctionPlatformChatMessage
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IAuctionPlatformChatMessage = {
  /**
   * Unique identifier of the chat message.
   *
   * @example
   *   123e4567-e89b-12d3-a456-426614174000
   */
  id: string & tags.Format<"uuid">;

  /** Foreign key to auction room id where the chat is posted. */
  auction_platform_auction_room_id: string & tags.Format<"uuid">;

  /** Foreign key to team leader posting this message. */
  auction_platform_team_leader_id: string & tags.Format<"uuid">;

  /** Unique ID from Chijijik API for this chat message. */
  chijijik_message_id: string;

  /** The actual chat message content. */
  message: string;

  /** Name of the message sender. */
  sender_name: string;

  /**
   * Creation timestamp of the message.
   *
   * @example
   *   2025-09-15T12:34:56.789Z
   */
  created_at: string & tags.Format<"date-time">;

  /** Last update timestamp for the message. */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft delete timestamp - null if active.
   *
   * @nullable
   */
  deleted_at: (string & tags.Format<"date-time">) | null;
};
export namespace IAuctionPlatformChatMessage {
  /**
   * Request schema for searching and paginating chat messages.
   *
   * Includes filters by auction room, team leader, message content, date
   * ranges, etc.
   */
  export type IRequest = {
    /**
     * Auction room ID to filter messages.
     *
     * @nullable
     */
    auction_platform_auction_room_id?:
      | (string & tags.Format<"uuid">)
      | undefined;

    /**
     * Team leader ID filter.
     *
     * @nullable
     */
    auction_platform_team_leader_id?:
      | (string & tags.Format<"uuid">)
      | undefined;

    /**
     * Filter chat messages containing this substring.
     *
     * @nullable
     */
    message_search?: string | undefined;

    /**
     * Start timestamp for filtering messages.
     *
     * @nullable
     */
    created_at_start?: (string & tags.Format<"date-time">) | undefined;

    /**
     * End timestamp for filtering messages.
     *
     * @nullable
     */
    created_at_end?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Page number for pagination.
     *
     * @nullable
     */
    page?: number | undefined;

    /**
     * Number of records per page.
     *
     * @nullable
     */
    limit?: number | undefined;

    /**
     * Sort order string, e.g., 'created_at desc'.
     *
     * @nullable
     */
    order_by?: string | undefined;
  };

  /**
   * Payload to create a new chat message.
   *
   * Contains necessary foreign keys and message content. Fields id,
   * created_at, updated_at, deleted_at are system managed.
   */
  export type ICreate = {
    /** Auction room ID where this chat message belongs. */
    auction_platform_auction_room_id: string & tags.Format<"uuid">;

    /** Team leader ID posting this message. */
    auction_platform_team_leader_id: string & tags.Format<"uuid">;

    /** Unique chat message ID from Chijijik system. */
    chijijik_message_id: string;

    /** Chat message content. */
    message: string;

    /** Sender's display name. */
    sender_name: string;
  };

  /**
   * Payload to update existing chat message.
   *
   * All fields optional to allow partial update except id which is path
   * param.
   */
  export type IUpdate = {
    /**
     * Updated auction room ID.
     *
     * @nullable
     */
    auction_platform_auction_room_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /**
     * Updated team leader ID.
     *
     * @nullable
     */
    auction_platform_team_leader_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /**
     * Updated Chijijik message ID.
     *
     * @nullable
     */
    chijijik_message_id?: string | null | undefined;

    /**
     * Updated chat message content.
     *
     * @nullable
     */
    message?: string | null | undefined;

    /**
     * Updated sender name.
     *
     * @nullable
     */
    sender_name?: string | null | undefined;

    /**
     * Updated deletion timestamp to soft delete or restore message.
     *
     * @nullable
     */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };
}
