import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";
import { patcheventRegistrationAdminEventAttendees } from "../../../../providers/patcheventRegistrationAdminEventAttendees";
import { AdminAuth } from "../../../../decorators/AdminAuth";
import { AdminPayload } from "../../../../decorators/payload/AdminPayload";
import { geteventRegistrationAdminEventAttendeesEventAttendeeId } from "../../../../providers/geteventRegistrationAdminEventAttendeesEventAttendeeId";
import { puteventRegistrationAdminEventAttendeesEventAttendeeId } from "../../../../providers/puteventRegistrationAdminEventAttendeesEventAttendeeId";
import { deleteeventRegistrationAdminEventAttendeesEventAttendeeId } from "../../../../providers/deleteeventRegistrationAdminEventAttendeesEventAttendeeId";

import { IPageIEventRegistrationEventAttendee } from "../../../../api/structures/IPageIEventRegistrationEventAttendee";
import { IEventRegistrationEventAttendee } from "../../../../api/structures/IEventRegistrationEventAttendee";

@Controller("/eventRegistration/admin/eventAttendees")
export class EventregistrationAdminEventattendeesController {
  /**
   * Search and retrieve a filtered, paginated list of event attendees.
   *
   * Retrieve a filtered and paginated list of event attendees. This operation
   * supports complex queries for event attendee data from the
   * event_registration_event_attendees table, which records confirmed users
   * registered for events. It includes references to associated events and
   * regular users, with creation and update timestamps.
   *
   * Access to this operation requires roles of admin or eventOrganizer,
   * reflecting their need to review attendees. Proper authorization checks are
   * mandatory to enforce data privacy.
   *
   * The response provides summarized attendee data conducive for management
   * dashboards or listings.
   *
   * @param connection
   * @param body Search criteria and pagination parameters for event attendees
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @AdminAuth()
    admin: AdminPayload,
    @TypedBody()
    body: IEventRegistrationEventAttendee.IRequest,
  ): Promise<IPageIEventRegistrationEventAttendee.ISummary> {
    try {
      return await patcheventRegistrationAdminEventAttendees({
        admin,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve detailed information of a specific event attendee by ID.
   *
   * Retrieve detailed information of a specific event attendee identified by
   * eventAttendeeId. The record includes event and user associations from
   * event_registration_event_attendees.
   *
   * Authorization is limited to admin and eventOrganizer roles to protect
   * sensitive registration details.
   *
   * Returns full attendee data or an error if not found.
   *
   * @param connection
   * @param eventAttendeeId Unique identifier of the event attendee record
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":eventAttendeeId")
  public async at(
    @AdminAuth()
    admin: AdminPayload,
    @TypedParam("eventAttendeeId")
    eventAttendeeId: string & tags.Format<"uuid">,
  ): Promise<IEventRegistrationEventAttendee> {
    try {
      return await geteventRegistrationAdminEventAttendeesEventAttendeeId({
        admin,
        eventAttendeeId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update event attendee information.
   *
   * This API operation updates information for a particular event attendee
   * identified by the path parameter 'eventAttendeeId'. The underlying database
   * entity is event_registration_event_attendees, which links confirmed
   * attendees to events.
   *
   * Users with the appropriate authorization role can update the attendee
   * record details. This might include changes to the association or
   * timestamps. The API expects a valid UUID format ID to identify the attendee
   * record.
   *
   * All updates must comply with database constraints ensuring event and user
   * relationships remain consistent. Timestamps should reflect the time of
   * modification to maintain auditability.
   *
   * Validation includes confirming the attendee exists and the provided update
   * data matches the Prisma schema field types.
   *
   * @param connection
   * @param eventAttendeeId Unique identifier of the event attendee to update
   * @param body Information needed to update an event attendee record
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":eventAttendeeId")
  public async update(
    @AdminAuth()
    admin: AdminPayload,
    @TypedParam("eventAttendeeId")
    eventAttendeeId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IEventRegistrationEventAttendee.IUpdate,
  ): Promise<IEventRegistrationEventAttendee> {
    try {
      return await puteventRegistrationAdminEventAttendeesEventAttendeeId({
        admin,
        eventAttendeeId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Delete an event attendee registration by ID. This is a permanent deletion
   * removing the attendee's event registration record.
   *
   * Authorized roles for this operation include regularUser (the attendee),
   * admin, and eventOrganizer.
   *
   * There is no request or response body.
   *
   * This operation does not perform soft deletion.
   *
   * @param connection
   * @param eventAttendeeId Unique identifier of the event attendee registration
   *   to delete
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":eventAttendeeId")
  public async erase(
    @AdminAuth()
    admin: AdminPayload,
    @TypedParam("eventAttendeeId")
    eventAttendeeId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteeventRegistrationAdminEventAttendeesEventAttendeeId({
        admin,
        eventAttendeeId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
